### ISSUE TITLE
Support newer versions of werkzeug?

### ISSUE THREAD

**Issue by alex** [mapproxy/mapproxy#1000]
mapproxy currently requires version 1.0.1 of werkzeug. This version is more than 4 years old, and has a number of security issues.

It'd be helpful if mapproxy supported newer versions of werkzeug.

Ideally it would be great to support version 3, but if that's not possible, than supporting 2.2.3 would be helpful.

**Comment by hblitza** [comment]
Hi alex, nice issue number #1000  - yes good catch. We would be happy if you have capacities to come up with a PR?

**Comment by ricardogsilva** [comment]
+1 for this, as I also found myself in need of it. Submitted a PR with the change, to get the ball rolling
