### ISSUE TITLE
"OperationalError: too many SQL variables" when reprojecting caches

### ISSUE THREAD

**Issue by stevendlander** [mapproxy/mapproxy#113]
I have a mixed mode cache of geodetic tiles from levels 9-21 that I would like to reproject into a new cache of web mercator tiles for the same zoom level range.

ftblissmainpostwm:
    sources: [ftblissmainpost]
    grids: [webmercatorLL]
    format: image/png
    cache:
      type: mbtiles
      filename: /data/Geopackages/ftblisswm.mbtiles
  ftblissmainpost:
    sources: []
    grids: [geodeticUL]
    format: mixed
    image:
      mode: RGBA
      colors: 0
      encoding_options:
        jpeg_quality: 75
    request_format: image/png
    cache:
      type: mbtiles
      filename: /data/packages/FtBlissMainPost-9to21.mbtiles

I get "OperationalError: too many SQL variables" when trying to seed this cache.  It looks like small integer zoom levels will seed fine, but zoom level ~5 and beyond results in this error.

Stack trace shows this error happening in a cursor.execute(stmt, coords) call for the cache in question.

**Comment by olt** [comment]
The root cause is that the seeding coverage was not valid for EPSG:3857.
