### ISSUE TITLE
Firewall problem

### ISSUE THREAD

**Issue by lionelbargeot** [mapproxy/mapproxy#127]
Hi, 
we work with a firewall product called checkpoint. When activating some http filtering options, we encountered problems with rejected packet generated by mapproxy. Demo pages en services description url did'nt work properly.

Mapproxy version : 1.6.0 (newer version not tested).
FW error messages : illegal header format detected: Malformed HTTP protocol name in response
FW solution : This error message is associated with the configurable parameters in the HTTP Protocol Inspection, that provides strict enforcement of the HTTP protocol, ensuring these sessions comply with RFC standards and common security practices.
Listed below are measures that can/cannot be applied, based on given conditions: 
Illegal HTTP version - No workaround exists. The HTTP request cannot be parsed correctly.
Malformed start line - No workaround exists. The HTTP request cannot be parsed correctly.
Start line without a URL - No workaround exists. The HTTP request cannot be parsed correctly.

Desactivating http filtering on our FW made MapProxy working fine again.
Regards
Lionel

**Comment by olt** [comment]
I'm closing this issue because it is no really possible to debug this without access to the firewall.
