### ISSUE TITLE
Limiting requests across hemispheres

### ISSUE THREAD

**Issue by keithamoss** [mapproxy/mapproxy#13]
A bit of an edge case here (apologies for the pun).

We've noticed an issue with requests from MapProxy that hit the boundary between eastern and western hemispheres. MapProxy is stopping the requests at the boundary, but in cases where the request is in the eastern hemisphere the upper right corner of the BBOX is being set to -180, not 180 (the eastern hemisphere's side of the boundary). This is causing some unfortunate display issues with our backend (MapServer).

For example:

Reprojected to EPSG:900913 (note the low quality of the image) 
http://srss-ows-1.landgate.wa.gov.au/wxs/firewatch.php?styles=&format=image%2Fpng&height=1184&bbox=14636773.6723,-5400734.67052,20037508.3428,391357.58482&transparent=True&layers=layer37_MODIS_Global_Mosaic.ecw&service=WMS&width=1104&request=GetMap&srs=EPSG%3A900913&version=1.1.1

The same request in native EPSG:4326 fails because the BBOX is invalid
http://srss-ows-1.landgate.wa.gov.au/wxs/firewatch.php?styles=&format=image%2Fpng&height=1184&bbox=131.484375,-43.580391,-180,3.513421&transparent=True&layers=layer37_MODIS_Global_Mosaic.ecw&service=WMS&width=1104&request=GetMap&srs=EPSG:4326&version=1.1.1

But if we replace the -180 with 180 we get the desired outcome:
http://srss-ows-1.landgate.wa.gov.au/wxs/firewatch.php?styles=&format=image%2Fpng&height=1184&bbox=131.484375,-43.580391,180,3.513421&transparent=True&layers=layer37_MODIS_Global_Mosaic.ecw&service=WMS&width=1104&request=GetMap&srs=EPSG:4326&version=1.1.1

This is possibly something MapServer should deal with, but we thought we'd ask for a fix from MapProxy first since it seems like such an easy fix from your POV.

We've worked around it for the time being by reducing our meta_size to 3,3 from 4,4 so only New Zealand is being pixelated, but a longer-term fix would be great.

**Comment by olt** [comment]
Closing this as there were some changes related to this.
