### ISSUE TITLE
Configure additional HTTP response headers

### ISSUE THREAD

**Issue by ezze** [mapproxy/mapproxy#160]
I installed recent MapProxy (1.7.1) on Ubuntu 14.04 LTS following [this guide](http://mapproxy.org/docs/latest/install.html). Everything works - I can get test OSM layer's tiles through MapProxy. But in order to use this layer on my web page I have to add additional response header:

    Access-Control-Allow-Origin: http://my-domain

I found [headers](http://mapproxy.org/docs/latest/configuration.html#headers) option in the documentation but it's meant to

> add additional HTTP headers to all requests to your sources

but not response headers of MapProxy itself.

So I can't use it right now without ability to specify HTTP response headers of MapProxy. Could it be implemented?

P.S. GIS StackExchange [related question](http://gis.stackexchange.com/questions/112451/how-to-add-additional-http-response-headers).

**Comment by olt** [comment]
MapProxy now sets ``Access-Control-Allow-Origin: *`` and you can configure this header with ``access_control_allow_origin`` in `globals.http`.

For other headers use the web server configuration as quiqua mentioned.
