### ISSUE TITLE
Support WMS wrapDateLine parameter

### ISSUE THREAD

**Issue by SpidermanInAK** [mapproxy/mapproxy#161]
![service](https://cloud.githubusercontent.com/assets/8752809/4306912/9627ea5e-3e84-11e4-919d-c28f886dfc1e.png)
Please support the WMS wrapDateLine parameter such that data at the 180th/International Date Line is seamless not disjointed.  We have a potential fix but lack Python expertise.

**Comment by olt** [comment]
wrapDateLine is an OpenLayer option. For issues at the anti-meridian see #187
