### ISSUE TITLE
Provide an example on how to properly set coverage / bbox for MBTiles

### ISSUE THREAD

**Issue by Prindle19** [mapproxy/mapproxy#167]
Would it be possible to have an example, expected configuraiton example for serving MBTiles? MapProxy's performance for doing this is quite good, and I feel like it is very close to being a great experience.

If I use the following configuration, WMS works fine when requested over an area of coverage in the MBTIles database, but, the GetCapabilities returns a global extent for the WMS layer. Also, without any sort of coverage / bbox set, TMS does not work.

services:
  demo:
  tms:
    use_grid_names: true
    # origin for /tiles service
    origin: 'nw'
  kml:
      use_grid_names: true
  wmts:
  wms:
    md:
      title: MapProxy WMS Proxy
      abstract: This is a minimal MapProxy example.
layers:
- name: mbtilesdemo
  title: Demo MBTiles
  sources: [mbtile_cache]

caches:
  mbtile_cache:
    grids: [webmercator]
    sources: []
    cache:
      type: mbtiles
      filename: /MBTiles/MBTiles.mbtiles
grids:
    webmercator:
        base: GLOBAL_MERCATOR

If I add a bbox to the grid, like below, the WMS layer will now have the proper extent, but the WMS will not actually return an image. However, TMS will now work.

services:
  demo:
  tms:
    use_grid_names: true
    # origin for /tiles service
    origin: 'nw'
  kml:
      use_grid_names: true
  wmts:
  wms:
    md:
      title: MapProxy WMS Proxy
      abstract: This is a minimal MapProxy example.
layers:
- name: mbtilesdemo
  title: Demo MBTiles
  sources: [mbtile_cache]

caches:
  mbtile_cache:
    grids: [webmercator]
    sources: []
    cache:
      type: mbtiles
      filename: /MBTiles/MBTiles.mbtiles
grids:
    webmercator:
        base: GLOBAL_MERCATOR
        bbox_srs: 'EPSG:4326'
        bbox: [-84.49172974,39.57367471,-84.04403687,39.92421883]

**Comment by olt** [comment]
For reference: This is only possible with a coverage on the source.
