### ISSUE TITLE
mapproxy returns 404 when running under uwsgi

### ISSUE THREAD

**Issue by nextstopsun** [mapproxy/mapproxy#169]
I'm having a problem running mapproxy under uwsgi + nginx.

Everything works ok when I start my configuration with `mapproxy-util serve-develop`. The server starts and I get tiles, demo page etc. All requests are being logged as usual.
But when I run an app under uwsgi, I get a strange page with `not found` text and a 404 code on any request to the app. This page doesn't look like it's an nginx standard 404.

Strange thing is that I don't see any requests in mapproxy log at all - just server start messages.
But uwsgi logs contain a 404 error:

```
[pid: 24213|app: 0|req: 2/4] 192.168.0.20 () {40 vars in 684 bytes} [Tue Nov 18 00:02:56 2014] GET /bm => generated 9 bytes in 2 msecs (HTTP/1.1 404) 2 headers in 86 bytes (1 switches on core 0)
```

But I'm not sure if it's generated with mapproxy or uwsgi itself.

I've tried a python test app with uwsgi and it works just fine.

I've also tried with default minimal yaml configuration fie from `/usr/local/lib/python2.7/dist-packages/MapProxy-1.7.1-py2.7.egg/mapproxy/config_template/paster/etc/mapproxy.yaml` - but I get the same 404 `not found` page.

My config is here: https://gist.github.com/nlebedev/daf09cdc55298864d619
Please help me someone.

**Comment by alfredbe** [comment]
I want to run MultiMapProxy under uwsgi and Nginx. Can you help me at this point by sending the config files?
