### ISSUE TITLE
Layer-source with non-english characters

### ISSUE THREAD

**Issue by Andarki** [mapproxy/mapproxy#175]
This is tested in Mapproxy 1.6.0 on Windows.

Layer definition: (spaces omitted due to Markdown)

> layers:
> name: Other-objects
> title: Other objects
> sources: ['wms_trans:Øvrige_objekter']

When Mapproxy is started, it shuts down immediately with the following information in the log:

> 2015-03-11 09:42:30,322 - INFO - mapproxy.config - reading: c:\mapproxy\mapproxy.yaml
> 2015-03-11 09:42:30,338 - WARNING - mapproxy.config - u'wms_trans:\xd8vrige_objekter' in layers[3].sources[0] not of type str
> 2015-03-11 09:42:30,338 - CRITICAL - mapproxy.config - invalid configuration

This is caused by the character 'Ø' which in the log appears as \xd8.
I have attempted to save mapproxy.yaml with ansi/utf8/utf8-signatures encodings, which makes no difference.
I have also tried escaping the Ø character with both \xF8 and \u00D8 which also makes no difference.

**Comment by olt** [comment]
Further discussion on the ML: http://lists.osgeo.org/pipermail/mapproxy/2015-March/002046.html

**Comment by olt** [comment]
Latest master now encodes the query string as UTF-8, so your example should not fail anymore. It doesn't mean that it now works though.
The WMS spec doesn't specify an encoding. More recent URI/URL RFCs define UTF-8 as the default encoding, but I bet that some servers are expecting something else.
