### ISSUE TITLE
GetFeatureinfo not passing FEATURE_COUNT

### ISSUE THREAD

**Issue by caviarbag** [mapproxy/mapproxy#177]
I had issues with mapproxy not passing this parameter to backend wms. Problem is present in both 1.7.1 and 1.8.0a nightly. #11 probably includes an attempt to fix this but I had to do one additional change in client/wms.py line 145 (tested in 1.8.0a nightly)
`info_query = InfoQuery(info_bbox, query.size, info_srs, info_pos, query.info_format, feature_count=query.feature_count)`

**Comment by olt** [comment]
Thanks for the report. It was not implemented for feature info requests that were transformed to another projection.
