### ISSUE TITLE
Python 3 support

### ISSUE THREAD

**Issue by Jenselme** [mapproxy/mapproxy#179]
I saw [here](https://raw.githubusercontent.com/mapproxy/mapproxy/master/CHANGES.txt) that python 3 support should arrive this year with version 1.8.0. Do you have a more precise release date?

If you need some help to port or to test, please let me know.

**Comment by olt** [comment]
1.8.0 is due in the next days/weeks. You can already test it with Python 3 by installing a "nightly" (see http://mapproxy.org/download)

**Comment by Jenselme** [comment]
OK, thanks!
