### ISSUE TITLE
Have the 'online_resource' metadata for WMS service defaulted to the service URL if not described

### ISSUE THREAD

**Issue by bferreol** [mapproxy/mapproxy#180]
To simplify the configuration of a WMS service, the 'online_resource' metadata (mandatory by the WMS specification) could be defaulted to the service URL if this one is not described in the yaml MapProxy configuration file.

Note; This could also resolve the problem identified at
http://osdir.lowified.com/mapproxy-gis/2012-02/msg00016.html

**Comment by bferreol** [comment]
I suggest the following modification in the wms templates files wms100capabilities.xml, wms110capabilities.xml, wms111apabilities.xml and wms130capabilities.xml:

    {{if service.online_resource}}
      <OnlineResource xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="{{service.online_resource}}"/>
    {{else}}
      <OnlineResource xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="{{service.url}}"/>
    {{endif}}

**Comment by olt** [comment]
OnlineResource is empty if it is not defined in the configuration. So the Capabilities are still valid.
The metadata OnlineResource (different than the DCP OnlineResource) should point to a website for this service. So I'm not sure how a link to the service is helpful.

**Comment by bferreol** [comment]
On a GetCapabilities request to the WMS service, my concern is that the GetCapabilities, GetMap and GetFeatureInfo DCP OnlineResource are guest from the service URL, but not the metadata OnlineResource. The metatada Service OnlineResource is filled from the 'online_resource' configuration key.
By looking at the WMS specifications (at least 1.1.1 of OGC), the OnlineResource should always contains a valid URL (chapter 6..2.2). In this condition, the 'online_resource' configuration key should be filled. In a concern of simplifying the deployment of the MapProxy product, the 'online-resource' configuration should so contains a valid URL (http://my-host/ blah, blah, ...). But in the majority of case, this is the service URL. That's why I suggest to guess the metada OnlineResource if not described in configuration file.

**Comment by olt** [comment]
Ok. I just checked with the XML DTD and it allowed empty OnlineResources.
Thanks for the pull request!
