### ISSUE TITLE
CouchDBCache funtion overloaded

### ISSUE THREAD

**Issue by JohnPurviance** [mapproxy/mapproxy#184]
On line 1009 of mapproxy/mapproxy/config/loader.py the function CouchDBCache is called with lock_dir=self.lock_dir(). In the function definition on line 53-57 of mapproxy/mapproxy/cache/couchdb.py this is not included. This causes a runtime error. On my local install I removed lock_dir=self.lock_dir from line 1009 of mapproxy/mapproxy/config/loader.py and have not noticed any issues, although I have not heavily tested this.

**Comment by masda70** [comment]
Same problem, same fix here. Using python 2.7.4, MapProxy 1.8 available on PyPI.
