### ISSUE TITLE
Autoconfig cannot generate service yaml without contact field in XML

### ISSUE THREAD

**Issue by JohnPurviance** [mapproxy/mapproxy#186]
I came across this bug while proxying one MapProxy into another. When using the autoconfig tool it would not allow me to generate a yaml without the services:wms:md:contact:person key populated in the MapProxy instance I was bringing into the other instance. I was able to bring the service In once I added the contact person to the wms md portion of the yaml. While I understand that it is not common for users to proxy MapProxy services through MapProxy this bug will still exist if you bring a MapProxy wms into another GIS tool that expects that tag in the XML. Further, this is also an issue when a user tries to setup a MapProxy service from a map server that is not from MapProxy, really any map service that does not have a contact person will cause the autoconfig tool to fail and show the stack trackback. Either MapProxy needs to populate a null contact person by default if one is not provided or it needs to not have a run time error when it cannot find a contact person in a wms get capabilities xml.

**Comment by olt** [comment]
This should have been fixed with 564ecbead8d3fa93416f6b100a30a15a2072c07b
Can you try to install a nightly (1.8.x, see http://mapproxy.org/download)?
