### ISSUE TITLE
Antimeridian issues

### ISSUE THREAD

**Issue by alpha-beta-soup** [mapproxy/mapproxy#187]
I've put this on StackExchange to cast the net a bit wider: http://gis.stackexchange.com/questions/155654/mapproxy-and-the-anitmeridian

**Comment by olt** [comment]
Copying the answer from StackExchange:

> Anti-meridian behavior is undefined in MapProxy right now (1.8). For most users it's is not an issue and so no one invested time or money to work on this. I know that this is not great for people from "the edge of the world" and I hope that this will change in the future.
