### ISSUE TITLE
mapproxy-util serve-develop does not work on Windows when installed with recent pip

### ISSUE THREAD

**Issue by olt** [mapproxy/mapproxy#189]
pip changed the way console_scripts are installed and the reloader of serve-develop is now unable to start itself.

**Comment by hannesaddec** [comment]
Make a copy of <<mappoxy-util.exe>> as <<mapproxy-util>> and it started for me.

**Comment by tobi238** [comment]
copying + renaming the 'mapproxy-util.exe' worked for me too :+1:

**Comment by olt** [comment]
Fixed with 63b00f7a1730e02e7c6aa5d76be6829b2723e9a6
