### ISSUE TITLE
Implement a S3 Cache

### ISSUE THREAD

**Issue by walkermatt** [mapproxy/mapproxy#19]
Hi,

I've been looking at implementing an AWS S3 Cache backend based on the FileCache, I now have a working prototype which uses boto and I'd appreciate any thoughts and feedback. The code can be found here in the s3 branch: https://github.com/walkermatt/mapproxy/tree/s3.

If you'd like to set up an S3 cache then you'll need the [boto package](http://docs.pythonboto.org/) and a cache of type 's3' and a valid bucket name. For instance to configure the demo osm_cache to use an S3 cache:

```yaml
caches:
  osm_cache:
    grids: [GLOBAL_MERCATOR, global_geodetic_sqrt2]
    sources: [osm_wms]
    cache:
      type: s3
      bucket: uniquebucketid
```

The bucket ID must be unique across all of S3 as described [here](http://docs.pythonboto.org/en/latest/s3_tut.html#creating-a-bucket) so choose something unique. At present new buckets are created in the EU zone, I'll no doubt make that configurable soon.

Even though you can store any arbitrary data in S3 against a key I've chosen to effectively store files with the keys being the effective file system path. This may allow an existing cache to be uploaded to S3 using something like s3fs or even offline import then used / maintained by the S3 cache.

BTW The original motivation for looking at an S3 cache is to set up a redundant shared cache used by several MapProxy instances all running the same configuration behind a load balancer. At present I'm using file based cache stored on EBS volumes which works well but results in duplication of the cache data. I've experimented with using s3fs with a file based cache but I've had several stability issues where the s3fs mount disappeared periodically.

Cheers,

Matt.

**Comment by pthorin** [comment]
Wouldn't this be better handled as a pull request? 
I would really like s3 as a cache backend as well, but I'm unsure how up to date this feature would be since it is about 3 years since this issue was created.

**Comment by walkermatt** [comment]
Hi, I've not used this in production as I think the [implementation](https://github.com/walkermatt/mapproxy/blob/s3/mapproxy/cache/s3.py) could use a little work. Feel free to test / update.

**Comment by olt** [comment]
I merged an updated version.
