### ISSUE TITLE
Custom origin for tile source

### ISSUE THREAD

**Issue by j16sdiz** [mapproxy/mapproxy#192]
Some tile source (e.g. those from ArcGis tile server) have an alternative "origin".
Projects like [Proj4Leaflet](https://github.com/kartena/Proj4Leaflet) allow a offset like this:

```
// SWEREF 99 TM with map's pixel origin at (218128.7031, 6126002.9379)
var crs = new L.Proj.CRS('EPSG:3006',
  '+proj=utm +zone=33 +ellps=GRS80 +towgs84=0,0,0,0,0,0,0 +units=m +no_defs',
  {
    origin: [218128.7031, 6126002.9379],  // custom origin point
    resolutions: [8192, 4096, 2048],
  }
);
```

Would be great if mapproxy can support the same `origin` option

**Comment by olt** [comment]
Origin is not supported but you can create an equivalent tile grid with the bbox parameter.

**Comment by j16sdiz** [comment]
Can I?
With a `bbox`, coordinate on the west of origin is out of bound and invalid.
Proj4leaflet allows that.

**Comment by olt** [comment]
You should be able to configure any grid that is also supported by Leaflet or OpenLayers.
If you need help with that configuration, then please ask on the mailing list.

If you think there is a bug with how MapProxy calculates a tile grid with the bbox parameter, then please describe how the origin parameter works in Leaflet and how would it solve that issue.
