### ISSUE TITLE
improving sqlite/mbtile performance

### ISSUE THREAD

**Issue by masda70** [mapproxy/mapproxy#196]
After noticing I could not saturate the CPU with a `sqlite` seeding task on a non-SSD drive, I decided to investigate further.

I pinned down this performance issue to the `store_tile` method in`mbtiles.py:MBTilesCache` to the use of a `db.commit()` after each INSERT to the SQLite database.

So I tried reducing the number of calls to `db.commit()` by adding a counter and only making a COMMIT after something like 100 INSERTS. Obviously this is problematic when using a concurrency factor >= 2 or the mapproxy app is running and a client is making a tile request (since the database will be locked).
In my case this is not a problem since I'm running the seeding task offline and I manage to do concurrency by using multiple seed tasks (e.g. for different caches / different zoom levels), so I run the seeding task with `-c 1`.

Regardless, I'm facing a second issue. After my change, I started getting more frequent "database is locked" errors that were interrupting the seeding task. I discovered that the seeding main thread was making SELECT calls to the database to check if a tile is cached before inserting it to the worker task queue (`_walk` in `seeder.py`, under `handle_uncached`). I decided to deactivate this check (this is done by the worker task anyway). However this might not ideal since the problem will persist when doing a cleanup task (`handle_stale`). Perhaps COMMIT calls could be deferred to the `store_tiles` methods which already commands multiple INSERTs (depending on the meta_tile size?), but this does not seem to be a simple task due to the architecture of the seed task which cannot ensure that only one zoom level is sent to the `store_tiles method.

**Comment by masda70** [comment]
In the end I ended up with a clean solution without noticeable drawbacks.
I added the following method to `MBTilesLevelCache`:

```
    def store_tiles(self, tiles):
        all_succeed = True
        mbtiles = {}
        for tile in tiles:
            level = tile.coord[2]
            mbtile = self._get_level(level)
            mbtiles[level] = mbtile
            if not mbtile.store_tile(tile, commit = False):
                all_succeed = False
        for level, mbtile in mbtiles.iteritems():
            mbtile.db.commit()
        return all_succeed
```

Also, I extended `store_tile` on both `MBTilesCache` and `MBTilesLevelCache` to take a extra argument  `commit` that defaults to false.

For instance on `MBTilesCache`,  `self.db.commit()` is conditioned on the value of the `commit` argument.
```
    def store_tile(self, tile, commit = True):
        [...]
                if self.supports_timestamp:
                    stmt = "INSERT OR REPLACE INTO tiles (zoom_level, tile_column, tile_row, tile_data, last_modified) VALUES (?,?,?,?, datetime(?, 'unixepoch', 'localtime'))"
                    cursor.execute(stmt, (level, x, y, content, time.time()))
                else:
                    stmt = "INSERT OR REPLACE INTO tiles (zoom_level, tile_column, tile_row, tile_data) VALUES (?,?,?,?)"
                    cursor.execute(stmt, (level, x, y, content))
                if commit:
                    self.db.commit()
            [...]
```

Finally, on `MBTilesLevelCache`, the argument is forwarded to the `MBTilesCache.store_tile` method:

```
    def store_tile(self, tile, commit = True):
        if tile.stored:
            return True

        return self._get_level(tile.coord[2]).store_tile(tile, commit)
```

Additionally, I tried adding a `cleanup` method to `MBTilesLevelCache`. For some reason, this was never implemented, the result is that SQLite databases are never closed when using a `sqlite` cache (unlike the `mbtiles` one). However, I did not retain this change since it can only slow down the performance of the seed task, without any noticeable benefit.

```
    # Cleanup mbtiles (close connections to SQLite Databases)
    def cleanup(self):
        for level,mbtile in self._mbtiles.iteritems():
            mbtile.cleanup()
```

**Comment by seandepagnier** [comment]
did you make a pull request for this?

**Comment by masda70** [comment]
No. I was expecting someone to reply before submitting my solution. I was not entirely sure that my solution the good approach, although it worked in my particular use-case.
Are you interested in this solution ?

**Comment by seandepagnier** [comment]
My biggest problem is re-running seeds with lots of coverage takes forever for mapproxy to scan the database before it even grabs any tiles.  It can take hours for example as I have thousands of coverages.

 I think your case is different because you noticed the slowdown when writing.  My issue is the speed of scanning.

**Comment by olt** [comment]
I'll be working on bulk store for SQLite/MBtiles this week. So this issue should be solved soon.

**Comment by olt** [comment]
Tiles are now stored in bulk for SQLite and MBTiles. For tiled sources you need to enable bulk_meta_tiles (see: https://mapproxy.org/docs/nightly/configuration.html#bulk-meta-tiles)
