### ISSUE TITLE
mapproxy-seed with --summary option does not write/delete to disk

### ISSUE THREAD

**Issue by hannesaddec** [mapproxy/mapproxy#201]
installed mappproxy with #189 on windows in virtualenv and it runs fine:
(mapproxy) G:\apps\virtualenv\mapproxy\mymapproxy>mapproxy-util serve-develop EC
_test.yaml
[2015-10-28 11:34:51,821] mapproxy.config - INFO - reading: G:\apps\virtualenv\m
approxy\mymapproxy\EC_test.yaml
[info]  * Running on http://127.0.0.1:8080/ (Press CTRL+C to quit)
[info]  * Restarting with reloader
[2015-10-28 11:34:52,444] mapproxy.config - INFO - reading: G:\apps\virtualenv\m
approxy\mymapproxy\EC_test.yaml

Issue 1: 
The usage of commandline switch --summary seems to perform a dry run. see below for proof. 

HINT: update documentation that --summary is a dry run or check argument handling.  

HINT: Additionally it's strange to see that caches from 0..15 are deleted, even if they are not exist on disk. Expected behaviour would be to say:  "found cache for level XX and deleted it." 

(mapproxy) G:\apps\virtualenv\mapproxy\mymapproxy>dir -b G:\apps\virtualenv\mapp
roxy\mymapproxy\cache_data\osm_cache_4326_EPSG4326
 Volume in drive G is Apps
 Volume Serial Number is 4C96-6618

 Directory of G:\apps\virtualenv\mapproxy\mymapproxy

File Not Found

 Directory of G:\apps\virtualenv\mapproxy\mymapproxy\cache_data\osm_cache_4326_E
PSG4326

28/10/2015  11:16    <DIR>          .
28/10/2015  11:16    <DIR>          ..
28/10/2015  11:12    <DIR>          02
28/10/2015  11:12    <DIR>          03
28/10/2015  11:16    <DIR>          04
28/10/2015  11:16    <DIR>          05
               0 File(s)              0 bytes
               6 Dir(s)  200.036.835.328 bytes free

(mapproxy) G:\apps\virtualenv\mapproxy\mymapproxy>mapproxy-seed -f EC_test.yaml
-s seed.yaml --summary --clean mycleanOSM_4326
========== Seeding tasks ==========
========== Cleanup tasks ==========
  mycleanOSM_4326:
    Cleaning up cache 'osm_cache_4326' with grid 'epsg4326' in EPSG:4326
    Limited to coverage in: -20.00000, 30.00000, 35.00000, 70.00000 (EPSG:4326)
    Levels: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 1
9]
    Remove: tiles older than 2015-10-28 12:00:33.871000

(mapproxy) G:\apps\virtualenv\mapproxy\mymapproxy>dir -b G:\apps\virtualenv\mapp
roxy\mymapproxy\cache_data\osm_cache_4326_EPSG4326
 Volume in drive G is Apps
 Volume Serial Number is 4C96-6618

 Directory of G:\apps\virtualenv\mapproxy\mymapproxy

File Not Found

 Directory of G:\apps\virtualenv\mapproxy\mymapproxy\cache_data\osm_cache_4326_E
PSG4326

28/10/2015  11:16    <DIR>          .
28/10/2015  11:16    <DIR>          ..
28/10/2015  11:12    <DIR>          02
28/10/2015  11:12    <DIR>          03
28/10/2015  11:16    <DIR>          04
28/10/2015  11:16    <DIR>          05
               0 File(s)              0 bytes
               6 Dir(s)  200.037.883.904 bytes free

(mapproxy) G:\apps\virtualenv\mapproxy\mymapproxy>mapproxy-seed -f EC_test.yaml
-s seed.yaml --clean mycleanOSM_4326
========== Cleanup tasks ==========
Start cleanup process (1 task)
  mycleanOSM_4326:
    Cleaning up cache 'osm_cache_4326' with grid 'epsg4326' in EPSG:4326
    Limited to coverage in: -20.00000, 30.00000, 35.00000, 70.00000 (EPSG:4326)
    Levels: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 1
9]
    Remove: tiles older than 2015-10-28 12:00:48.083000
[12:00:48] removing old tiles in cache_data\osm_cache_4326_EPSG4326\00
[12:00:48] removing old tiles in cache_data\osm_cache_4326_EPSG4326\01
[12:00:48] removing old tiles in cache_data\osm_cache_4326_EPSG4326\02
[12:00:48] removing old tiles in cache_data\osm_cache_4326_EPSG4326\03
[12:00:48] removing old tiles in cache_data\osm_cache_4326_EPSG4326\04
[12:00:48] removing old tiles in cache_data\osm_cache_4326_EPSG4326\05
[12:00:48] removing old tiles in cache_data\osm_cache_4326_EPSG4326\06
[12:00:48] removing old tiles in cache_data\osm_cache_4326_EPSG4326\07
[12:00:48] removing old tiles in cache_data\osm_cache_4326_EPSG4326\08
[12:00:48] removing old tiles in cache_data\osm_cache_4326_EPSG4326\09
[12:00:48] removing old tiles in cache_data\osm_cache_4326_EPSG4326\10
[12:00:48] removing old tiles in cache_data\osm_cache_4326_EPSG4326\11
[12:00:48] removing old tiles in cache_data\osm_cache_4326_EPSG4326\12
[12:00:48] removing old tiles in cache_data\osm_cache_4326_EPSG4326\13
[12:00:48] removing old tiles in cache_data\osm_cache_4326_EPSG4326\14
[12:00:48] removing old tiles in cache_data\osm_cache_4326_EPSG4326\15
[12:00:48] removing old tiles in cache_data\osm_cache_4326_EPSG4326\16
[12:00:48] removing old tiles in cache_data\osm_cache_4326_EPSG4326\17
[12:00:48] removing old tiles in cache_data\osm_cache_4326_EPSG4326\18
[12:00:48] removing old tiles in cache_data\osm_cache_4326_EPSG4326\19

(mapproxy) G:\apps\virtualenv\mapproxy\mymapproxy>dir -b G:\apps\virtualenv\mapp
roxy\mymapproxy\cache_data\osm_cache_4326_EPSG4326
 Volume in drive G is Apps
 Volume Serial Number is 4C96-6618

 Directory of G:\apps\virtualenv\mapproxy\mymapproxy

File Not Found

 Directory of G:\apps\virtualenv\mapproxy\mymapproxy\cache_data\osm_cache_4326_E
PSG4326

28/10/2015  12:00    <DIR>          .
28/10/2015  12:00    <DIR>          ..
               0 File(s)              0 bytes
               2 Dir(s)  200.041.148.416 bytes free

(mapproxy) G:\apps\virtualenv\mapproxy\mymapproxy>

-----------------------------------------------------------------

Issue 2: 

specifying the summary option does not do anything on -seed. , however without it works. 

(mapproxy) G:\apps\virtualenv\mapproxy\mymapproxy>mapproxy-seed -f EC_test.yaml
-s seed.yaml --summary --seed myseedOSM_4326
========== Seeding tasks ==========
  myseedOSM_4326:
    Seeding cache 'osm_cache_4326' with grid 'epsg4326' in EPSG:4326
    Limited to coverage in: -20.00000, 30.00000, 35.00000, 70.00000 (EPSG:4326)
    Levels: [1, 2]
    Overwriting: no tiles
========== Cleanup tasks ==========

(mapproxy) G:\apps\virtualenv\mapproxy\mymapproxy>dir -b G:\apps\virtualenv\mapp
roxy\mymapproxy\cache_data\osm_cache_4326_EPSG4326
 Volume in drive G is Apps
 Volume Serial Number is 4C96-6618

 Directory of G:\apps\virtualenv\mapproxy\mymapproxy

File Not Found

 Directory of G:\apps\virtualenv\mapproxy\mymapproxy\cache_data\osm_cache_4326_E
PSG4326

28/10/2015  12:00    <DIR>          .
28/10/2015  12:00    <DIR>          ..
               0 File(s)              0 bytes
               2 Dir(s)  200.040.624.128 bytes free

(mapproxy) G:\apps\virtualenv\mapproxy\mymapproxy>mapproxy-seed -f EC_test.yaml
-s seed.yaml --seed myseedOSM_4326
========== Seeding tasks ==========
Start seeding process (1 task)
  myseedOSM_4326:
    Seeding cache 'osm_cache_4326' with grid 'epsg4326' in EPSG:4326
    Limited to coverage in: -20.00000, 30.00000, 35.00000, 70.00000 (EPSG:4326)
    Levels: [1, 2]
    Overwriting: no tiles
[12:07:26]  1   0.00% -20.00000, 30.00000, 35.00000, 70.00000 (0 tiles) ETA: N/A

[12:07:26]  2   0.00% -20.00000, 30.00000, 35.00000, 70.00000 (0 tiles) ETA: N/A
(mapproxy) G:\apps\virtualenv\mapproxy\mymapproxy>dir -b G:\apps\virtualenv\mapp
roxy\mymapproxy\cache_data\osm_cache_4326_EPSG4326
 Volume in drive G is Apps
 Volume Serial Number is 4C96-6618

 Directory of G:\apps\virtualenv\mapproxy\mymapproxy

File Not Found

 Directory of G:\apps\virtualenv\mapproxy\mymapproxy\cache_data\osm_cache_4326_E
PSG4326

28/10/2015  12:07    <DIR>          .
28/10/2015  12:07    <DIR>          ..
28/10/2015  12:07    <DIR>          01
28/10/2015  12:07    <DIR>          02
               0 File(s)              0 bytes
               4 Dir(s)  200.040.869.888 bytes free

(mapproxy) G:\apps\virtualenv\mapproxy\mymapproxy>

[12:07:26]  1 100.00% -20.00000, 30.00000, 35.00000, 70.00000 (32 tiles) ETA: 20
15-10-28-12:07:26

HINT: update documentation that --summary is a dry run or check argument handling.  

----------------------------------------------------------
seed.yaml

seeds:
  myseedOSM_4326:
    caches: [osm_cache_4326]
    grids: [epsg4326]
    # coverages: []
    levels: [1,2]  
      
cleanups:
  mycleanOSM_4326:
    caches: [osm_cache_4326]
    

coverages:

----------------------------------------
EC_test.yaml
services:
  demo:
  tms:
    use_grid_names: true
    # origin for /tiles service
    origin: 'nw'
  kml:
      use_grid_names: true
  wmts:
  wms:
    md:
      title: MapProxy WMS Proxy
      abstract: This is a minimal MapProxy example.

layers:
  - name: osm3857
    title: OSM native
    sources: [osm_cache_in]
  - name: osm4326
    title: OSM in WGS84
    sources: [osm_cache_4326]
  - name: osm4258
    title: OSM in ETRS89_DD
    sources: [osm_cache_4258]
  - name: osm3035
    title: OSM in ETRS89_LAEA
    sources: [osm_cache_3035]
  - name: mapnik3857
    title: direct mapnik at 3857
    sources: [mapnik_cache]

caches:
  osm_cache_4326:
    grids: [epsg4326]
    meta_size: [4, 4]
    sources: [osm_cache_in]

  osm_cache_4258:
    grids: [epsg4258]
    meta_size: [4, 4]
    sources: [osm_cache_in]

  osm_cache_3035:
    grids: [epsg3035]
    meta_size: [4, 4]
    sources: [osm_cache_in]

  osm_cache_in:
    grids: [osm_grid]
    #disable_storage: true
    sources: [osm_source]

  mapnik_cache:
    grids: [osm_grid]
    sources: [mapnik_source]

sources:
  osm_source:
    type: tile
    grid: osm_grid
    concurrent_requests: 1
    # url: http://a.tile.openstreetmap.org/%(z)s/%(x)s/%(y)s.png
    url: http://europa.eu/webtools/maps/tiles/osm-ec/%(z)s/%(x)s/%(y)s.png

  mapnik_source:
    type: mapnik
    mapfile: S:\\osm-rendering\\mapnik-europe.xml
    transparent: true

grids:
 epsg4326:
    srs: 'EPSG:4326'
    bbox: [-20, 30, 35, 70]
    bbox_srs: 'EPSG:4326'
    origin: 'nw'

 epsg4258:
    srs: 'EPSG:4258'
    bbox: [-20, 30, 35, 70]
    bbox_srs: 'EPSG:4326'
    origin: 'nw'

 epsg3035:
    srs: 'EPSG:3035'
    bbox: [-20, 30, 35, 70]
    bbox_srs: 'EPSG:4326'
    origin: 'nw'
 
 utm32n:
    srs: 'EPSG:25832'
    bbox: [4, 46, 16, 56]
    bbox_srs: 'EPSG:4326'
    origin: 'nw'
    min_res: 5700

 osm_grid:
    base: GLOBAL_MERCATOR
    origin: nw

**Comment by olt** [comment]
This issue is pretty hard to read, please check out the formatting options of GitHub: https://guides.github.com/features/mastering-markdown/

And yes, the ``--summary`` option does not seed. See http://mapproxy.org/docs/nightly/seed.html

**--summary** *Print a summary of all seeding and cleanup tasks and exit.*

**Comment by hannesaddec** [comment]
My innocent suggestion for the summary documentation would be:
--summary Print a summary of all seeding and cleanup tasks without requesting, creating or removing any tiles and exit.
