### ISSUE TITLE
mapproxy-seed retrieve additional scale levels

### ISSUE THREAD

**Issue by hannesaddec** [mapproxy/mapproxy#202]
We observe that the specified levels . e.g. levels: [9,10] are sometimes trigger error messages and try to retrieve level 13 (see below) - for the [1,2] case we had error messages that a zoom level of 4 are to be retrieved. 

Question:
- [ ] Is the cache level handling correct ?  Is it a misconception that the zoom levels e.g. between EPSG:4326 and EPSG:3857 should be almost similar ? I would not expect to see a trigger for a call to zoom level 13? 

Configuration: windows machine with virtualenv. 

Proof of Behaviour: 
1. (mapproxy) G:\apps\virtualenv\mapproxy\mymapproxy>mapproxy-seed -f EC_test.yaml -s seed_9_2_10.yaml --seed myseedOSM_4326
========== Seeding tasks ==========
Start seeding process (1 task)
  myseedOSM_4326:
    Seeding cache 'osm_cache_4326' with grid 'epsg4326' in EPSG:4326
    Limited to coverage in: -20.00000, 30.00000, 35.00000, 70.00000 (EPSG:4326)
    Levels: [9, 10]
    Overwriting: no tiles
[12:08:45]  9   0.00% -20.00000, 69.14062, -19.14062, 70.00000 (0 tiles) ETA: N/
A
[12:08:45] 10   0.00% -20.00000, 69.57031, -19.57031, 70.00000 (0 tiles) ETA: N/
A
[2015-10-28 12:08:45,437] mapproxy.source.tile - WARNING - could not retrieve ti
le: HTTP Error "http://europa.eu/webtools/maps/tiles/osm-ec/13/3640/1839.png": 5
04

FIles which have been used in the configuration are below

seed.yaml

seeds:
  myseedOSM_4326:
    caches: [osm_cache_4326]
    grids: [epsg4326]
    # coverages: []
    levels: [1,2]  
      
cleanups:
  mycleanOSM_4326:
    caches: [osm_cache_4326]
    

coverages:

----------------------------------------
EC_test.yaml
services:
  demo:
  tms:
    use_grid_names: true
    # origin for /tiles service
    origin: 'nw'
  kml:
      use_grid_names: true
  wmts:
  wms:
    md:
      title: MapProxy WMS Proxy
      abstract: This is a minimal MapProxy example.

layers:
  - name: osm3857
    title: OSM native
    sources: [osm_cache_in]
  - name: osm4326
    title: OSM in WGS84
    sources: [osm_cache_4326]
  - name: osm4258
    title: OSM in ETRS89_DD
    sources: [osm_cache_4258]
  - name: osm3035
    title: OSM in ETRS89_LAEA
    sources: [osm_cache_3035]
  - name: mapnik3857
    title: direct mapnik at 3857
    sources: [mapnik_cache]

caches:
  osm_cache_4326:
    grids: [epsg4326]
    meta_size: [4, 4]
    sources: [osm_cache_in]

  osm_cache_4258:
    grids: [epsg4258]
    meta_size: [4, 4]
    sources: [osm_cache_in]

  osm_cache_3035:
    grids: [epsg3035]
    meta_size: [4, 4]
    sources: [osm_cache_in]

  osm_cache_in:
    grids: [osm_grid]
    #disable_storage: true
    sources: [osm_source]

  mapnik_cache:
    grids: [osm_grid]
    sources: [mapnik_source]

sources:
  osm_source:
    type: tile
    grid: osm_grid
    concurrent_requests: 1
    # url: http://a.tile.openstreetmap.org/%(z)s/%(x)s/%(y)s.png
    url: http://europa.eu/webtools/maps/tiles/osm-ec/%(z)s/%(x)s/%(y)s.png

  mapnik_source:
    type: mapnik
    mapfile: S:\\osm-rendering\\mapnik-europe.xml
    transparent: true

grids:
 epsg4326:
    srs: 'EPSG:4326'
    bbox: [-20, 30, 35, 70]
    bbox_srs: 'EPSG:4326'
    origin: 'nw'

 epsg4258:
    srs: 'EPSG:4258'
    bbox: [-20, 30, 35, 70]
    bbox_srs: 'EPSG:4326'
    origin: 'nw'

 epsg3035:
    srs: 'EPSG:3035'
    bbox: [-20, 30, 35, 70]
    bbox_srs: 'EPSG:4326'
    origin: 'nw'
 
 utm32n:
    srs: 'EPSG:25832'
    bbox: [4, 46, 16, 56]
    bbox_srs: 'EPSG:4326'
    origin: 'nw'
    min_res: 5700

 osm_grid:
    base: GLOBAL_MERCATOR
    origin: nw

**Comment by olt** [comment]
This issue is pretty hard to read, please check out the formatting options of GitHub: https://guides.github.com/features/mastering-markdown/

**Comment by hannesaddec** [comment]
Well, i updated formatting, however yaml files can not be attached to the  ticket. :-1: .

**Comment by olt** [comment]
You can mark ```code blocks``` with triple-backticks, this will keep the indention.

I see that you are reprojecting different tile grids. Each tile grid has different zoom levels/resolutions. So it's ok that grid A at level 9 needs tiles from level 13 of grid B.
