### ISSUE TITLE
Mapproxy WMTS rendering in ArcGIS 10.3

### ISSUE THREAD

**Issue by rmn0001** [mapproxy/mapproxy#203]
I have been working on a mapproxy WMS/WMTS service for imagery. Everything has gone relatively smooth, except for when loading the WMTS service in ArcMap. Certain tiles are blurry and never adjust resolution when changing scale. However, the WMTS service works fine in QGIS and even ArcGIS Online. What could I be missing in my configuration? Or is there another issue I am not aware of? Any help or guidance is extremely appreciated. Link to the demo page: http://162.222.183.191:8080/demo/

![services](https://cloud.githubusercontent.com/assets/15380842/10831902/426776c4-7e56-11e5-9cd9-9e4340dad458.JPG)

![layers](https://cloud.githubusercontent.com/assets/15380842/10831908/4c04d122-7e56-11e5-98be-9e88316792e2.JPG)

![caches](https://cloud.githubusercontent.com/assets/15380842/10831916/5522ccdc-7e56-11e5-84b6-ead6cef8e891.JPG)

![sources](https://cloud.githubusercontent.com/assets/15380842/10831924/5ce6cf86-7e56-11e5-8dfe-a4f25abdb523.JPG)

![grids](https://cloud.githubusercontent.com/assets/15380842/10831934/66f53274-7e56-11e5-8008-cabc4e2d98c6.JPG)

**Comment by olt** [comment]
Not sure if I can help you here. You should post you question on the mailing list, if you can't get any help from Esri. Maybe an ArcGIS user can help you.

BTW: You increase the likelihood that someone helps you, if they don't have to write down your configuration from the screenshots. See also 'How to ask for help' http://mapproxy.org/support
