### ISSUE TITLE
Coverage documentation for polygons

### ISSUE THREAD

**Issue by pierocampa** [mapproxy/mapproxy#204]
The *Coverages* [docs](http://mapproxy.org/docs/1.8.0/coverages.html#polygon-file) talk about the `datasource` parameter for a WKT polygon input, while in the *Sources* [examples](http://mapproxy.org/docs/1.8.0/sources.html#example-configuration) I also see the:

    polygons: GM.txt
    polygons_srs: EPSG:900913

...option, which is not documented in *Coverages*.. That's all.

**Comment by olt** [comment]
It's the old way:

> New in version 1.5.0: MapProxy can autodetect the type of the coverage. You can now use coverage instead of the bbox, polygons or ogr_datasource option. The old options are still supported.

I changed the examples to use `datasource`. Thanks!
