### ISSUE TITLE
Supporting sources with multiple servers

### ISSUE THREAD

**Issue by rowanwins** [mapproxy/mapproxy#206]
Hi there, 

Thanks for a great project, I've got a question about how to deal with tile sources that have tiles on multiple sub-domains.

So for example in leaflet you can do something like
````
var tilelayer = L.tileLayer('http://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', {
   subdomains: [0,1,2]
})
````

Is there a way I can handle this in my yaml file?

Thanks,
Rowan

**Comment by olt** [comment]
No, that's not supported.
Are you sure you need this? Subdomains are typically used as a workaround for browser limitations.

**Comment by rowanwins** [comment]
Thanks for the info. I was never entirely sure what the logic behind the multiple subdomains was so that's good to know.
