### ISSUE TITLE
Memory leak in mapproxy-seed

### ISSUE THREAD

**Issue by ramunasd** [mapproxy/mapproxy#208]
Running seed process memory usage grows, not very fast, but it can consume a lot.
In my environment `pmap` shows something like this:
```
Address           Kbytes     RSS   Dirty Mode   Mapping
0000000000400000       0    1076       0 r-x--  python2.7
0000000000871000       0       0       0 r----  python2.7
0000000000872000       0     200     140 rw---  python2.7
00000000008db000       0      56      56 rw---    [ anon ]
000000000247b000       0   11412   11412 rw---    [ anon ]
0000000004f43000       0   35452   35452 rw---    [ anon ]
00007fa87139c000       0      16       0 r-x--  libnss_dns-2.15.so
00007fa8713a3000       0       0       0 -----  libnss_dns-2.15.so
```

Only line `0000000004f43000` has growing numbers.

After some time, i got these numbers:
10000 tiles ~35Mb
25000 tiles ~120Mb
50000 tiles ~260Mb

I'm using version 1.8.1, riak as backend and wms as source.

**Comment by olt** [comment]
That's a lot.
I have a seed running with 7 million tiles at the moment and all processes are around 80MB. So it might be related to riak? Can you test it with another cache backend?

**Comment by ramunasd** [comment]
Yes, it's something with riak library. I tried both protocols but memory
leak is same. Thanks @olt, I'll ping riak community.

**Comment by ramunasd** [comment]
I found this memory leak is due to bug in thread storage, one example - http://stackoverflow.com/questions/8076752/memory-leak-when-using-shared-library-with-thread-local-storage-via-ctypes-in-a

I can't reproduce same leak when everything is performed in same thread. And leak is lower if threading.local() is removed from cache/riak.py

Python 3.4 works well without leaks and consumes even less memory. So solution is just migrate to latest python version.
