### ISSUE TITLE
support opacity for "tiles"-source&cache

### ISSUE THREAD

**Issue by powermik** [mapproxy/mapproxy#220]
i tried to merge two "tiles"-layer into one with opacity:

quick hack to  expand  the tile section in spec.py:449 to:

> 'tile': combined(source_commons, {
>                 required('url'): str(),
>                 'transparent': bool(),
>                 'image': combined(image_opts, {    'opacity': number()}),
>                 'grid': str(),
>                 'request_format': str(),
>                 'origin': str(), # TODO: remove with 1.5
>                 'http': http_opts,
>                 'on_error': on_error,
>             }),

seems to work. I have no idea if this is supposed to work so i did not created a pull request
is this the right way to do?

**Comment by olt** [comment]
No it isn't. :-) The spec is only for configuration validation and should not give you different behavior in MapProxy.
I'm closing this for now.
