### ISSUE TITLE
MBTiles cache seems to be corrupt

### ISSUE THREAD

**Issue by thedmi** [mapproxy/mapproxy#225]
During tests with an MBTiles cache I discovered that the produced MBTiles file is malformed. At first I thought that the problem is connected to the reprojection that I had in my example, but I was able to reproduce the problem without reprojection (all projections in web mercator).

Here is a minimal config (adapted from the included `mapproxy.yaml`) that reproduces the problem:

    services:
      demo:
      wmts:
        md:
          title: MapProxy WMS Proxy
          abstract: This is a minimal MapProxy example.

    layers:
      - name: osm
        title: Omniscale OSM WMS - osm.omniscale.net
        sources: [osm_cache_mbtiles]

    caches:
      osm_cache_mbtiles:
        grids: [webmercator]
        sources: [osm_wms]
        cache:
          type: mbtiles

    sources:
      osm_wms:
        type: wms
        req:
          # use of this source is only permitted for testing
          url: http://osm.omniscale.net/proxy/service?
          layers: osm

    grids:
        webmercator:
            base: GLOBAL_WEBMERCATOR

Note that running this example works when using mapproxy as tile server, so the demo application shows a correct map. However, loading the mbtiles file in LocusMap on Android or in QGIS produces a corrupted map:

![brokenmbtilesinqgis](https://cloud.githubusercontent.com/assets/1295139/14993813/f0e7cad8-116c-11e6-824e-3575c33381d4.png)

I also tried to load the mbtiles file with MapTiler. This doesn't work at all, MapTiler displays the following error message:

> MBTiles file is malformed. Missing metadata table, missing bounds value in metadata

I even tried it with an explicit bbox on the grid, but without luck. I'm using MapProxy 1.8.2 on Windows.

Any help would be appreciated.

**Comment by olt** [comment]
Can you try GLOBAL_MERCATOR as the grid? MBTiles counts tiles from bottom to top (origin: sw), AFAIK.

**Comment by thedmi** [comment]
MapTiler still shows the error that the file is malformed, but in LocusMap and QGIS the file works now. Thanks a lot.

**Comment by olt** [comment]
Great.
For MapTiler: This is more or less a missing feature in MapProxy. The metadata table is not complete, as the actual data boundary is not known for MapProxy in advance.

**Comment by seandepagnier** [comment]
I am using mapproxy-seed and get the same issue.   Is there some way to update the metadata table?
