### ISSUE TITLE
Cascading Mapproxy for different parts of the world

### ISSUE THREAD

**Issue by loomsen** [mapproxy/mapproxy#229]
Hello.

We are trying to set up a cascading Mapproxy installation, and have different backends serving different parts of the world. Like say a backend for Asia, a backend cluster for Europe...
Please see this gist:
https://gist.github.com/loomsen/613f076154e15e8639c029e2ad71be2f

However, the frontend seems to be off by one zoom level.

Proxy zoom level 0:
![selection_038](https://cloud.githubusercontent.com/assets/302524/15387016/02304e56-1dab-11e6-9b1a-a2cf1a6bac9f.png)
Backends zoom level 0:
![selection_039](https://cloud.githubusercontent.com/assets/302524/15387037/1ca64d08-1dab-11e6-961e-5a80593ba7fb.png)
Backends zoom level 1 - identical to proxy zoom level 0:
![selection_040](https://cloud.githubusercontent.com/assets/302524/15387055/345e8abe-1dab-11e6-9a2e-6defdcbf860f.png)

Also, this is how the demo looks like on zoom level 0:
![selection_041](https://cloud.githubusercontent.com/assets/302524/15387240/4e8b606e-1dac-11e6-9405-1c6d17c6f3b0.png)

Any pointers on how to accomplish this or why this is happening highly appreciated.

Regards

**Comment by olt** [comment]
Can you please use the mailing list for support questions? We use GitHub only for tracking bugs, feature requests, etc. Thanks!
