### ISSUE TITLE
ImageServer generates invalid request

### ISSUE THREAD

**Issue by ingenieroariel** [mapproxy/mapproxy#235]
Example of a request that returns a valid image:

When using the new ArcGIS functionality (#221) with a public ImageServer I ran into the following problem:
 
`https://ngamaps.geointapps.org/arcgis/rest/services/NEPAL/Kathmandu_DEM_PreEvent/ImageServer/exportImage?bbox=312122.1901381541%2C3042391.0217958903%2C359082.1901381541%2C3085231.0217958903&bboxSR=&size=&imageSR=&time=&format=png&pixelType=F32&noData=&noDataInterpretation=esriNoDataMatchAny&interpolation=+RSP_BilinearInterpolation&compression=&compressionQuality=&bandIds=&mosaicRule=&renderingRule=&f=image`

Example of the requests that MapProxy generates:

`https://ngamaps.geointapps.org/arcgis/rest/services/NEPAL/Kathmandu_DEM_PreEvent/ImageServer/export?f=image&grid=default_grid&bbox=-20037508.3428,-20037508.3428,20037508.3428,20037508.3428&format=png&bboxSR=3857&size=512,512&transparent=True&imageSR=3857`

[arcgis2.txt](https://github.com/mapproxy/mapproxy/files/340503/arcgis2.txt)

**Comment by olt** [comment]
The URL endpoint differs: exportImage vs export?!

**Comment by ingenieroariel** [comment]
Yeah, I could not get the other endpoint to work at all and had to look at
the examples generated by arcgis on that instance.

**Comment by waybarrios** [comment]
I was able to render a result by doing:

```diff --git a/mapproxy/request/arcgis.py b/mapproxy/request/arcgis.py
index 6acae96..25c0739 100644
--- a/mapproxy/request/arcgis.py
+++ b/mapproxy/request/arcgis.py
@@ -96,6 +96,14 @@ class ArcGISRequest(BaseRequest):
         self.url = self.url.rstrip("/")
         if not self.url.endswith("export"):
             self.url += "/export"
+        # if it's an ImageServer, make sure it uses exportImage
+        if 'ImageServer' in url:
+            self.url +="Image"
+            # Append a few things to fixed_params, like
+            self.fixed_params['noDataInterpretation']='esriNoDataMatchAny'
+            self.fixed_params['interpolation']='+RSP_BilinearInterpolation'
+            self.fixed_params['pixelType']='F32'
+
 
     def copy(self):
         return self.__class__(param=self.params.copy(), url=self.url)```

**Comment by iandees** [comment]
The code was designed to handle MapServers, not ImageServers.

MapServers support the `/export` URL extension while ImageServers only support `/exportImage`. This is a pretty string suffix check.

**Comment by olt** [comment]
fff5b385d42485dfdd88642b817dce2e7e2d9dd0 improves the selection of the right URL endpoint for ImageServer.

interpolation, pixelType and noDataInterpretation depend on the actual service. I've documented that you can add these parameters to the `req` option. 

The Kathmandu_DEM_PreEvent service is no longer available. The ArcGIS example service [1] works however (even without any further options).

[1] http://sampleserver3.arcgisonline.com/ArcGIS/rest/services/World/MODIS/ImageServer

**Comment by ingenieroariel** [comment]
Thanks @olt

I'll close this issue and test with a bunch of ImageServers out there. If I find any issues I'll open a more targeted ticket.

cc @JorgeMartinezG
