### ISSUE TITLE
Mapnik & LockTimeout on spawning

### ISSUE THREAD

**Issue by aberenyi** [mapproxy/mapproxy#236]
Hi,

Sorry to necrobump an old GitHub issue, but it seems that I'm facing the same problem described here: https://github.com/mapproxy/mapproxy/issues/76

The main difference is that I'm not using Apache's mod_wsgi, but using spawning as the WSGI server.

Any idea how to pass `WSGIApplicationGroup %{GLOBAL}` to the spawning conf?

While looking for a solution, I found this old [thread](http://www.mail-archive.com/mapnik-users@lists.berlios.de/msg04024.html), so I'm going to rebuild `lxml` without thread support as see if it helps.

Package versions:
- MapProxy 1.8.2
- mapnik 2.2.0.654.g718a8b3-5 (also tried with 2.2.0.655.g1b0f4d6-4 same result)

**Comment by olt** [comment]
Did you have any success? Can I close this issue?

**Comment by aberenyi** [comment]
@olt sorry, I completely forgot about this.

Interestingly the issue was Mapnik related, some of the labels could not be drawn due to some styling issue and that resulted in a weird tile lock error.

In the meantime I've switched to MapProxy 1.9.0 w/ Mapnik3 and Python3, replaced spawning with gunicorn + aiohttp. 

Everyhing works just fine now.
