### ISSUE TITLE
mapproxy creates world-writable directories/files in its cache ?

### ISSUE THREAD

**Issue by landryb** [mapproxy/mapproxy#237]
Using 1.8.0, when creating subdirs/tiles, by default mapproxy creates them with 777 mode, owner/group www-data:www-data (the latter coming from gunicorn) - this isnt great security-wise, as anyone is allowed to write to the cache dir, which .. could be a security issue.

It would be much nicer to create directories with 755 mode (or 775, but i doubt there's a usecase) and files with 644 mode.

**Comment by landryb** [comment]
https://docs.python.org/2/library/os.html#os.makedirs -> the default mode is 0777, and os.makedirs is used in mapproxy/util/fs.py:ensure_directory()

For files, open() is used in mapproxy/util/fs.py:write_atomic(), and i dont see where the default mode is.. or there's an issue with umask not being applied somewhere ?

**Comment by olt** [comment]
This should be an issue with your system configuration as the umask should prevent that the files are world-writable.

**Comment by landryb** [comment]
Well, i have no specific system configuration about umask, that's a default debian jessie setup..

**Comment by landryb** [comment]
I'd like to reopen this ticket, there should be imo a fix directly within mapproxy. When used via gunicorn/wsgi, the umask given to gunicorn doesnt seem to be used, and thus dirs end up with mode 777. mapproxy itself should use sane defaults (755), and not the silly 0777 mode python defaults to.

**Comment by landryb** [comment]
And there should be a real bug somewhere, because if i enable debug logging, i see 'umask: 22' in the `[DEBUG] Current configuration:` section, so umask is propagated from gunicorn  config (where i have --umask=0022 in the flags), but the directories are still created with mode 777. Maybe the umask isnt propagated to workers ?

**Comment by olt** [comment]
This sounds to me that it is a bug in gunicorn.
