### ISSUE TITLE
Bounding box dimensions undocumented

### ISSUE THREAD

**Issue by mryellow** [mapproxy/mapproxy#238]
https://mapproxy.org/docs/nightly/coverages.html

Bounding box example gives random numbers, yet nowhere is it described which of these are X/Y min/max.

**Comment by steamboatid** [comment]
still thereis NO explaination about BBOX

**Comment by olt** [comment]
It's closed because I added a description what value is x/y and min/max. See https://mapproxy.org/docs/nightly/coverages.html#bounding-box

**Comment by steamboatid** [comment]
I already read that page.
It only stated 
> bbox or datasource:
>A simple BBOX as a list of minx, miny, maxx, maxy, e.g: [4, -30, 10, -28] or as a string 4,-30,10,-28.

4,-30,10,-28 is dummy number right?
is there any real example on bbox?
I'm using srs: 'EPSG:4326'

how can I compute bbox using latitude and longitude?

**Comment by olt** [comment]
You can use QGIS to get a bounding box. Just click on the button next the Coordinate field and you should see the Extent: ![screen shot 2017-07-17 at 09 22 23](https://user-images.githubusercontent.com/235174/28258439-807cdaee-6ad1-11e7-98d4-387beb1290d5.png)

You need to change the colon to a comma and tell MapProxy in which projection (`srs`) this extent is.

**Comment by olt** [comment]
Or even simpler: http://bboxfinder.com

**Comment by steamboatid** [comment]
Great. it's good if we can put that infos at the manual page.
