### ISSUE TITLE
mapproxy-seed completes without all the tiles in coverage

### ISSUE THREAD

**Issue by seandepagnier** [mapproxy/mapproxy#243]
Often mapproxy-seed completes and must be run again and again until there are 0 tiles fetched.  It should not be "complete" or finished until the cache is completed.

**Comment by seandepagnier** [comment]
I am often seeing;

[2016-07-30 14:55:05,614] mapproxy.cache.mbtiles - WARNING - unable to store tile: database is locked

**Comment by olt** [comment]
I think the issues are related. MapProxy is unable to store a tile If the database is locked. So it will miss tiles that are required in a second seed. The locking issue is already discussed in other issues and on the mailing list.

**Comment by seandepagnier** [comment]
Why is it not caching the tile and queuing a job to store it in the main thread?

At least it could lock on accessing the database rather than throw the
data away and die.
