### ISSUE TITLE
Support "image/vnd.jpeg-png" format (GeoServer's "smart transparency" for WMS)

### ISSUE THREAD

**Issue by dalbani** [mapproxy/mapproxy#260]
It recently came to my attention that (the in-development version of) GeoServer supports a new `image/vnd.jpeg-png` format to provide "smart transparency" for WMS requests.
Here are some links to explain what I'm talking about:
http://www.geo-solutions.it/blog/geoserver-smart-transparency/
http://docs.geoserver.org/stable/en/user/services/wms/outputformats.html
https://github.com/geoserver/geoserver/commit/ba41769ec67202e18c7aabdeb685c69786508177

While MapProxy currently supports this smart transparency functionality when **serving** tiles, it would be nice to take advantage of it when fetching data from a remote WMS server that natively supports it.
What do you think?

**Comment by bartjkdp** [comment]
Added in https://github.com/mapproxy/mapproxy/pull/456
