### ISSUE TITLE
MBTiles cache is not storing tiles in TMS schema format

### ISSUE THREAD

**Issue by palmerj** [mapproxy/mapproxy#276]
As per the MapBox MBTiles specifications (https://github.com/mapbox/mbtiles-spec/blob/master/1.2/spec.md), the values used to locate tile should be in the TMS schema format. The current code is storing tiles in the XYZ format and not flipping the y value. e.g [mapproxy/cache/mbtiles.py](https://github.com/mapproxy/mapproxy/blob/master/mapproxy/cache/mbtiles.py#L165)

**Comment by olt** [comment]
The tile order depends on the configured grid. GLOBAL_MERCATOR uses the right TMS order. But you can even store WGS84 tiles in an `mbtiles` cache. The `sqlite` cache format is a better option for this, as it doesn't break any specs.

This should be mentioned in the documentation, or even print a warning. Can you provide a patch for that? An automatic fix however is not an option, as this would be a backwards incompatible change.

**Comment by palmerj** [comment]
Taken from the spec:

> The tiles table contains tiles and the values used to locate them. The zoom_level, tile_column, and tile_row columns follow the Tile Map Service Specification in their construction, but in a restricted form:
> The global-mercator (aka Spherical Mercator) profile is assumed

So MBTiles do not support non global-mercator grids - pretty black and white. But the user could use the SQLite cache and be ok.

> This should be mentioned in the documentation, or even print a warning. Can you provide a patch for that? 

I think what should be done is raise an error if the user tries to cache data from a non global-mercator grid. But I see the grid is not available within the object and is not currently passed into the constructor. But yes at least documenting this will help.

> An automatic fix however is not an option, as this would be a backwards incompatible change.

Current users who have used MBtiles for non global-mercator grids could be told to migrate their data to the correct format. Maybe a simple migration script that runs SQL update statement could fix this?

**Comment by olt** [comment]
> So MBTiles do not support non global-mercator grids - pretty black and white.

Yes, that's clear to me. I just meant that this is not enforced and a user is able to configure MapProxy to violate the spec. 

> I think what should be done is raise an error if the user tries to cache data from a non global-mercator grid.

Unfortunately, this is not an option. Backwards compatibility is a top priority and this "feature" is now available for 5 years. A deprecation warning would be OK.

**Comment by palmerj** [comment]
> Unfortunately, this is not an option. Backwards compatibility is a top priority and this "feature" is now available for 5 years. 

Ok thanks.

Could the other option be to create a new backend option for the MBTile cache (e.g schema_layout) that defines either 'xyz', or 'tms', with the default being 'xyz'. Then once a new major release happens the default could be changed so the cache conform with the specification.

**Comment by olt** [comment]
I don't understand :-/

You can change this already by using a different tile grid. GLOBAL_MERCATOR uses the 'tms' schema and GLOBAL_WEBMERCATOR uses the 'xyz' schema. GLOBAL_MERCATOR _is_ the default grid right now and the MBTiles example in the documentation also uses GLOBAL_MERCATOR.

**Comment by palmerj** [comment]
Ah right sorry I didn't understand your original comments and wasn't aware difference between teh GLOBAL_WEBMERCATOR and GLOBAL_MERCATOR grid. Problem solved - thanks!
