### ISSUE TITLE
SyntaxError after Restarting with reloader in Windows

### ISSUE THREAD

**Issue by gb96** [mapproxy/mapproxy#279]
For some reason it appears the reloader is attepting to launch `mapproxy-util.exe` with the Python interpreter, instead of just executing `mapproxy-util.exe`

Had a look at the source code in `mapproxy\util\ext\serving.py` but could not figure out what it was doing wrong.  Problem encountered in version 1.9.0 and still present in latest development tarball:

```
C:\app\mymapproxy>ver

Microsoft Windows [Version 6.1.7601]
C:\app\mymapproxy>python --version
Python 2.7.11 :: Continuum Analytics, Inc.
C:\app\mymapproxy>..\mapproxy_venv\Scripts\activate
(mapproxy_venv) C:\app\mymapproxy>mapproxy-util --version
MapProxy 1.10.0a0.post20161130
(mapproxy_venv) C:\app\mymapproxy>mapproxy-util serve-develop mapproxy.yaml
[2016-11-30 09:43:35,720] mapproxy.config - INFO - reading: C:\app\mymapproxy\mapproxy.yaml
[info]  * Running on http://127.0.0.1:8080/ (Press CTRL+C to quit)
[info]  * Restarting with reloader
  File "C:\app\mapproxy_venv\Scripts\mapproxy-util.exe", line 1
SyntaxError: Non-ASCII character '\x90' in file C:\app\mapproxy_venv\Scripts\mapproxy-util.exe on line 1, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details

```

**Comment by stanleyck** [comment]
I am also having the exact same problem. Any information on how to fix this would be greatly appreciated.

**Comment by olt** [comment]
Previous versions of PIP created mapproxy-util.exe and mapproxy-util.py. The reloader called `python mapproxy-util` and this loaded the .py file. More recent versions of PIP only created .exe files, but they were still Python files (or somehow directly executable by Python). I've updated MapProxy to call  `python mapproxy-util.exe`. Apparently PIP changed the way it installs scripts again.  

@stanleyck are you using Anaconda as well?

**Comment by stanleyck** [comment]
@olt: I'm not using anaconda. I'm just using python 2.7, and followed the install instructions as given in https://mapproxy.org/docs/1.9.0/install_windows.html. Running on Windows 7, 64bit.

**Comment by stanleyck** [comment]
I tried reinstalling python, and now using version 2.7.9, and now it works!

**Comment by KoAi** [comment]
I had same problem and it works too on python 2.7.9 (not with python 2.7.12), thanks @stanleyck

**Comment by m314** [comment]
I can also reproduce this problem.  I was able to get everything working while keeping Python 2.7.12 and Mapproxy 1.9, but I had to rollback `virtualenv` to 15.0.3 (was 15.1.0) and `setuptools` to 26.0.0 (was 28.8.0).

**Comment by olt** [comment]
There is a new 1.9.1 release which should fix this.

**Comment by gb96** [comment]
Thanks @olt :smile:
