### ISSUE TITLE
Misalignment in lower scales when reprojecting from EPSG:4326 to EPSG:3857 and viceversa

### ISSUE THREAD

**Issue by SantiagoHorcajo** [mapproxy/mapproxy#285]
Hi there,
## Context
In one of our projects we need to:
1. Expose the same service in two projections: EPSG:4326 and EPSG:3857
2. Overlay some vectors from ArcGIS Server 10.3.1 (EPSG:4326) over a raster service(EPSG:3857). So, when we expose the service as EPSG:4326, the WMTS raster service gets reprojected, and when we espose as EPSG:3857 is the vector ArcGIS Server service which is reprojected.
## Expected Behavior
We expected to match vectors over images at all scales and latitudes.
## Actual Behavior
At lower scales (zoom levels 0 to 5), we notice a great misalignment with greater latitudes.
For example, when exposed as EPSG:3857 we get the following invalid result at level 2 [3857level2](https://drive.google.com/file/d/0B3a135yKn4gDSnR4TFFBLVBteUk/view?usp=sharing), at level 3 also invalid [3857level3](https://drive.google.com/file/d/0B3a135yKn4gDaVlPV3BDUThIYzA/view?usp=sharing), and, finally, at level 6 the vector and image are nearly aligned [3857level6](https://drive.google.com/file/d/0B3a135yKn4gDeXNHcDlIdDhxVTQ/view?usp=sharing).
When exposed as EPSG:4326 we get the following invalid result at level 3 [4326level3](https://drive.google.com/file/d/0B3a135yKn4gDTjNHck9uZTZSSnM/view?usp=sharing), also invalid for level 4 [4326level4](https://drive.google.com/file/d/0B3a135yKn4gDdkVILWdtMC1Ocm8/view?usp=sharing) and nearly aligned for level 5 [4326level5](https://drive.google.com/file/d/0B3a135yKn4gDRXoxNmFtWlJuYWc/view?usp=sharing). Notice that for lower latitudes there's no misalignment.
## Steps to Reproduce
This is my .yaml file (sorry, can't expose in the internet the vector map service, but the raster one is an example from ESRI):
<pre>services:
  demo:
  wmts:
layers:
  - name: Hibrid3857
    title: Hibrid3857
    sources: [cache_hibrid3857]
  - name: Hibrid4326
    title: Hibrid4326
    sources: [cache_hibrid4326]
caches:
  cache_hibrid3857:
    grids: [webmercator]
    image:
      format: image/jpeg
    sources: [cache_raster3857, cache_vector3857]
    disable_storage: true
    cache:
      type: sqlite
  cache_hibrid4326:
    grids: [geodetic]
    image:
      format: image/jpeg
    sources: [cache_raster4326, cache_vector4326]
    disable_storage: true
    cache:
      type: sqlite
  cache_raster4326:
    grids: [geodetic]
    sources: [cache_raster3857]
    disable_storage: true
    cache:
      type: sqlite
  cache_raster3857:
    grids: [webmercator]
    sources: [src_raster3857]
    disable_storage: true
    cache:
      type: sqlite
  cache_vector3857:
    grids: [webmercator]
    image:
      format: image/png
      transparent: true
    sources: [cache_vector4326]
    disable_storage: true
    cache:
      type: sqlite
  cache_vector4326:
    grids: [geodetic]
    image:
      format: image/png
      transparent: true
    sources: [src_vector4326]
    disable_storage: true
    cache:
      type: sqlite
sources:
  src_raster3857:
    type: tile
    url: http://services.arcgisonline.com/arcgis/rest/services/World_Imagery/MapServer/tile/%(z)s/%(y)s/%(x)s
    on_error:
      other:
        response: transparent
        cache: false
  src_vector4326:
    type: arcgis
    req:
      url: http://arcgisterra/arcgis/rest/services/Vector/MapServer
      transparent: true
grids:
  geodetic:
    base: GLOBAL_GEODETIC
    origin: nw
  webmercator:
    base: GLOBAL_WEBMERCATOR

globals:
</pre>
## Your Environment
* MapProxy 1.9.0
* Operating system: Ubuntu 16.04

**Comment by olt** [comment]
MapProxy uses a fixed grid for raster transformations. This does not work well for extreme distortions.
A dynamic grid would improve the results for this specific case. (Similar to https://openlayers.org/en/latest/doc/tutorials/raster-reprojection.html)
