### ISSUE TITLE
MapProxy + Mapnik: Invalid width for image dimensions requested

### ISSUE THREAD

**Issue by tds4u** [mapproxy/mapproxy#290]
**MapProxy + Mapnik
Invalid width for image dimensions requested**

### Environment
```
MapProxy 1.9.1
Mapnik 3.0.12
/mapfiles/mapproxy # lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.10
Release:        16.10
Codename:       yakkety
```
mapproxy.yaml
```
# maximum output size for a WMS requests in pixel, default is 4000 x 4000
# compares the product, eg. 3000x1000 pixel < 2000x2000 pixel and is still
# permitted
max_output_pixels: [4000, 4000]
```
log files
```
[2017-02-09 13:08:13,770] API /var/www/XYZ/private/carto/osm-de.xml:(-20037508.342789244,18736244.373262405,-19362416.50897457,19460255.90517959):EPSG:3857:(1104,1184) 500 - 1881

2017-02-09 13:08:13,770 - ERROR - mapproxy.source.mapnik - could not render Mapnik map: Invalid width for image dimensions requested
```

## Context
On Debian 7 and 8 and Ubuntu 16.04 LTS no problems. Same configuration on 16.10 give that error and zoom level < 6 are not rendered.

## Expected Behavior
Should render image

## Actual Behavior
Doesn't render image

**Comment by tds4u** [comment]
I played around with source/mapnik.py AND:
If I remove "buffer-size" in Carto style the error is gone. Tested with changing query.size to e.g. 512x512 and no errors. But with buffer-size set and query.size at original 1104x1184 the error is raised.

PS: In mapnik.py there is a spelling mistake at then end ;-)
```
layer.name != 'Unkown' 
```

**Comment by olt** [comment]
Closing this issue for know.
Please reopen if the issue persists and if you can provide a (simple) way to reproduce this.
