### ISSUE TITLE
Versionconflict in requirements between WebTest and Six

### ISSUE THREAD

**Issue by LKajan** [mapproxy/mapproxy#292]
## Context
WebTest 2.0.10 needs six>=1.6.0 but requirements-test.txt is installing six 1.4.1

## Expected Behavior
pip install -r requirements-test.txt should complete.

## Actual Behavior
Installing gives VersionConflict error.

## Possible Fix
Is it ok to upgrade six to 1.6 or even 1.10?

## Your Environment

* Version used: master
* Environment name and version (e.g. Python 2.7.5 with mod_wsgi 4.5.9): python 3.4
* Operating System and version: Windows 10

**Comment by olt** [comment]
I did an (long overdue) update of all test requirements. Can you check again with the latest master?

**Comment by olt** [comment]
Closing this issue. Please reopen if the issue still exists.
