### ISSUE TITLE
Layers cannot be split across multiple yaml files when using list format layer config

### ISSUE THREAD

**Issue by rightway1** [mapproxy/mapproxy#293]
I have a large number of layers configured in mapproxy.yaml, and I want to split some of these into separate .yaml files using the base: [sub_file.yaml] option to make this easier to manage.

When using the deprecated dictionary format for the layers this seems to work as expected, and the layers from both files are listed in the demo page:
`
layers:
    mylayer1:
        ...
    mylayer2:
        ...
`

When using the recommended list format for the layers, only the layers defined in the master file seem to be available.  
`
layers:
    - name: mylayer1
        ...
    - name: mylayer2
        ...
`
If ALL layers are defined in the secondary file then they are recognised in the configuration, so it appears to be just the merger of the list format layer configurations which does not work.

I can work around this by using the deprecated dictionary format for now, but it would be good to have this base: [] approach working with the list format as well.

* Version used: MapProxy 1.9.1
* Python 3.4.4 with uWSGI 2.0.14; gcc 4.9.2
* Ubuntu 14.04:

**Comment by VonShtirlitz** [comment]
+1

**Comment by olt** [comment]
Lists are always overwritten as there is no _right_ way of merging lists, compared to dictionaries. 

Merge at the beginning or at the end? How to replace a list? What happens with duplicates? What happens with lists like ``bbox``?

I'm closing this issue for now. Please reopen if you like to implement a solution for that. Please start a discussion first that addresses the mentioned issues, before starting to code.

**Comment by danielklim** [comment]
Can we just implement merging at the highest level and do so naively (i.e. ignoring duplicates)? For example:

base_layers_1.yml:
`layers:
- name: layer_a
  title: title_a
  sources: [src_a]
`
base_layers_2.yml:
`layers:
- name: layer_b
  title: title_b
  [[etc...]]
- name: layer_a
  title: layer_a_duplicate

result.yml
- name: layer_a
  title: title_a
  [[etc...]]
- name: layer_b
  title: title_b
  [[etc...]]
# duplicate a not added since name already exists
`

**Comment by danielklim** [comment]
@rightway1 Old issue but in case you decide to revisit: I have run into this issue as well and for now, am just kludging by keeping a folder of partial layer confs, then running a preprocessing script to merge them all into a single layers file before loading them into the main mapproxy.yml

**Comment by nirnir93** [comment]
This is an old issue, but it's not yet resolved and I also require this use case and have a suggestion that may work:
In [`config/loader.py`](/mapproxy/mapproxy/blob/master/config/loader.py), make  `_legacy_layers_conf_dict` recursively call `_layers_conf_dict` (the documentation already suggests that `_layers_conf_dict` should be recursive)

This means that the `layers` dict syntax, which is now marked as deprecated, should be supported again (with a note that explains that using this syntax means that layer order is undefined and unexpected, but using the list syntax means having a single file containing all the layers)

If the `mapproxy` team is willing to support the deprecated dictionary syntax, I'd love to implement this suggestion.
(note that this syntax is deprecated for about a decade and survived a major release)

@olt

**Comment by tristndev** [comment]
Still an old issue, but I would vote to accept the merge request #567 as it adds the desired functionality. 👍🏼 

Until then: @danielklim - care to share your merging preprocessing script?
