### ISSUE TITLE
Cleaning Considers Levels Which Don't Exist

### ISSUE THREAD

**Issue by FilmCoder** [mapproxy/mapproxy#295]
Suppose I have a map service with levels 0 and 1 cached.  If I tell MapProxy to clean that service for levels 0 and 1, the cleaning happens very quickly.

However, if I tell mapproxy to clean that service levels 0 through 20, the cleaning may take many days.  However, it should be able to detect that there are only two levels cached, and delete those levels quickly.

## Steps to Reproduce
1.  Add a map service
2.  cache a layer in it for levels 0 and 1
3.  initiate a clean job for that layer for levels 0 through 20
4.  notice the clean job takes exceptionally long (days to delete 10 small files)?

**Comment by olt** [comment]
Please include _minimal_ but _complete_ configurations.
I can only guess: You are using coverages? See: https://mapproxy.org/docs/nightly/seed.html#id5
