### ISSUE TITLE
EPSG:3414 issue. "not compatible with TMS"

### ISSUE THREAD

**Issue by blinters** [mapproxy/mapproxy#303]
Not sure is it me or MapProxy has a limitation to convert from Global_WebMercator (Openstreetmap) to EPSG:3414? I have the exception stating that EPSG:3414 is not compatible with TMS. I am sure that my configuration is right.

reference: http://spatialreference.org/ref/epsg/3414/

Looking forward for help!

![epsg3414](https://cloud.githubusercontent.com/assets/15936817/25690169/19785d2c-30c1-11e7-81d6-2daa32e9b1a9.PNG)

**Comment by olt** [comment]
See: https://mapproxy.org/docs/nightly/configuration.html#origin

**Comment by blinters** [comment]
@olt I've taken a look at the origin but still quite unsure. 

I've check that EPSG:3414 Projected Bounds: 4257.9355, 11470.3186, 64359.3062, 49067.5413
so how should i configure the origin?

spatialreference: https://sirent.inlis.gov.sg/CoordinateSystems.aspx

cheers

**Comment by blinters** [comment]
@olt the fact is that I do not know whether EPSG:3414 is a "sw" or "nw" origin.

Would deeply appreciate for any kind help!

**Comment by olt** [comment]
The origin is an attribute of the grid and is independent of the actual projection.
Something like this should work (if you really need TMS and not WMTS):

    grids:
        mygrid:
            srs: 'EPSG:3414'
            bbox: [4257.9355, 11470.3186, 64359.3062, 49067.5413]
            origin: sw


Please use the mailing list for further questions as we use GitHub issues only for bugs.

**Comment by blinters** [comment]
@olt I got the origin working. However, I am still experiencing weird behavior of map in when i use the tms end point in arcgis.js webtiledlayer. The correct behavior should look like the image below (correct.png)

![correct](https://cloud.githubusercontent.com/assets/15936817/25832257/1719be52-349c-11e7-9bbe-f005aee89ff8.PNG)

This is the weird behavior in arcgis.js. What could be wrong? bug?

![wrong](https://cloud.githubusercontent.com/assets/15936817/25832258/171ce58c-349c-11e7-8369-63ce50fce96f.png)

**Comment by blinters** [comment]
@olt I got the origin working. However I am experiencing another weird behavior when I use the tms/tiles enpoint from mapproxy in arcgis.js webtilelayer. In the picture below, it works well in openlayers as you can see it in correct.png

![correct](https://cloud.githubusercontent.com/assets/15936817/25832495/7a13b318-349d-11e7-82eb-f1a2458fa2bc.PNG)

However, the behavior is weird when I feed the end point to arcgis.js webtiledlayer. What could be wrong? a limitation? or bug?

![wrong](https://cloud.githubusercontent.com/assets/15936817/25832527/a9827c7e-349d-11e7-8bb2-1bde10c7214b.png)

**Comment by olt** [comment]
See https://mapproxy.org/docs/nightly/services.html#tiled-map-services-tms for the difference between `/tms` and `/tiles`

**Comment by blinters** [comment]
@olt I change the end point and neither http://localhost:8080/**tiles**/1.0.0/sweden/EPSG3414/${z}/${x}/${y}.png nor http://localhost:8080/**tms**/1.0.0/sweden/EPSG3414/${z}/${x}/${y}.png did i see the correct behavior. Could it be configuration problem in yaml file? 

## Your Environment

services:
  demo:
  tms:
    use_grid_names: false
    #origin: 'sw'
layers:
  - name: sweden
    title: sweden
    sources: [cache_sweden]
    tile_sources: [cache_sweden]

caches:
  cache_sweden:
    sources: [cache_sweden_original]
    grids: [EPSG3414]
    meta_size: [4, 4]
    cache:
      type: mbtiles
  cache_sweden_original:
    sources: [source_sweden]
    grids: [GLOBAL_WEBMERCATOR ]
    disable_storage: true
sources:
  source_sweden:
    type: tile
    grid: GLOBAL_WEBMERCATOR   
    url: 'http://a.tile.openstreetmap.org/%(z)s/%(x)s/%(y)s.png'
    http:
      ssl_no_cert_checks: true
grids:
  EPSG3414:
    srs: 'EPSG:3414'

    bbox: [-675.5313466758907,18049.210543332632,67659.34292307265,50840.777726467]
    origin: sw
    tile_size: [256, 256]

globals:
  srs:
    # override system projection file
    proj_data_dir: 'C:\Users\PC\mymapproxy'
