### ISSUE TITLE
GeoPackage support for Multiple Layers

### ISSUE THREAD

**Issue by FilmCoder** [mapproxy/mapproxy#308]
On https://gitlab.com/GitLabRGI/nsg/gpep-mapproxy/issues/4, we're working to add support such that GeoPackages can be created with multiple layers of tile data.

Do any of you have any immediate recommendations on structure, best practices, etc... for adding in such a feature?  Particularly OLT, if there are any big nono's or yesyes's in how to add this feature in, letting me know would make a possible pull request into the main mapproxy repository smoother.

**Comment by olt** [comment]
Isn't that already possible with the filename and table_name option?

**Comment by FilmCoder** [comment]
This is already possible, this issue should be closed.
