### ISSUE TITLE
Missing __init__.py in MapProxy 1.10.0 wheel file (import error)

### ISSUE THREAD

**Issue by vog** [mapproxy/mapproxy#310]
## Context

When installing MapProxy via

    pip install MapProxy

(which installs the wheel file `MapProxy-1.10.0-py2.py3-none-any.whl`), the main package `mapproxy` has no `__init__.py`.

This is an issue when importing MapProxy though a local package source.

In that case, it is impossible to import any mapproxy modules:

    import mapproxy

## Expected Behavior

The above `import` statement runs without error message.

## Actual Behavior

    ImportError: No module named mapproxy

## Possible Fix

Ensure that the existing source file `mapproxy/__init__.py` is also present in the generated wheel files.

## Steps to Reproduce

Reproducing the issue (to be executed on a system where **MapProxy is not installed**):

    pip install --system -t libs MapProxy
    echo 'import mapproxy; print("OK")' > test.py
    PYTHONPATH=libs python test.py

Result:

    Traceback (most recent call last):
      File "test.py", line 1, in <module>
        import mapproxy; print("OK")
    ImportError: No module named mapproxy

Quick fix:

    touch libs/mapproxy/__init__.py
    PYTHONPATH=libs python test.py

Result:

    OK

## Context

I want to run MapProxy from within my own Python program without having to start it as a separate process through `subprocess.Popen()`.

## Your Environment

* Version used: MapProxy 1.10.0
* Environment name and version (e.g. Python 2.7.5 with mod_wsgi 4.5.9): Python 2.7.13
* Operating System and version: Debian

**Comment by olt** [comment]
It's related to namespace packages. There are three ways to implement them and MapProxy uses the  pkg_resources-style variation (the only variation available back then).
Apparently this is not compatible with wheels. I think we should change to the pkgutil-style for 1.11.

For more information: https://packaging.python.org/guides/packaging-namespace-packages/

**Comment by olt** [comment]
The namespace package is dropped with 7ed7b3e as it is not used (except for old versions of mapproxy-renderd).
