### ISSUE TITLE
Incorrect color in tile generation

### ISSUE THREAD

**Issue by torrespri** [mapproxy/mapproxy#311]
## Context

Hi, I'm a problem of the generation of Mapproxy tiles on a WMS service.
The WMS service https://www.sigua.ua.es/cgi-bin/siguawms2?
If you access the WMS image is good, but with seeding, the image has not generated the image correctly, it is in different of gray escales.
The problem is showed here https://www.sigua.ua.es/index.html?id=0018PB057

In these captures you can see the difference of colors, where there must be white, appears gray.
![645537](https://cloud.githubusercontent.com/assets/484175/26724520/2e474930-479a-11e7-882e-1c79935f5dad.png)

![captura de pantalla de 2017-06-02 12-53-14](https://cloud.githubusercontent.com/assets/484175/26724529/3db21dbe-479a-11e7-8e94-2d7099e9c148.png)

If I make TMS with QGIS with extension QMetaTiles the result is 
![645537](https://cloud.githubusercontent.com/assets/484175/26724634/d602940e-479a-11e7-9938-b44dcdb4fbb3.png)

Could you help me?

* Version used: Mapproxy 1.10
* Environment name and version: Python 2.7.43 
* Server type and version: 
* Operating System and version: Debian 7.11

**Comment by olt** [comment]
See https://mapproxy.org/docs/nightly/configuration.html#encoding-options, especially fastoctree and mediancut

**Comment by torrespri** [comment]
Thank you very much. I solved this issue with options to enable 24 bit PNG images and quantizer: fastoctree.
