### ISSUE TITLE
MaxWidth/MaxHeight not advertised in WMS Capabilities

### ISSUE THREAD

**Issue by fsteggink** [mapproxy/mapproxy#313]
In my MapProxy configuration files I'm setting max_output_pixels, like this:
```
services:
  wms:
    ...
    max_output_pixels: [5000, 5000]
    ...
```

Therefor I'm expecting that this will be translated to MaxWidth and MaxHeight elements in the WMS capabilities document (WMS 1.3.0 only). However, I'm missing these elements.

Seeing the implementation, when given a list, max_output_pixels is calculated by multiplying the first two values. So, when 5000x5000 pixels is valid (25M), then also requests of images of 6000x4000 pixels (24M) are valid.

I'd rather not alter the default behavior, so when a single integer is given, then it should be treated as such, although it would make sense to show the values as sqrt(max_output_pixels) in the Capabilities document. However, when a list of two (or more) integers is given, then in my opinion it should be treated as [MaxWidth, MaxHeight], and advertised as such.

I'm using MapProxy 1.10.

We're considering to submit a patch. Please let me know if this such a patch would be welcome.

**Comment by olt** [comment]
Yes, a patch for MaxWidth and MaxHeight in the 1.3.0 Capabilities is welcomed.
The current max_output_pixels behavior however should not be changed for backwards compatibility (it's also documented https://mapproxy.org/docs/nightly/services.html#max-output-pixels).

**Comment by drnextgis** [comment]
@olt what do you expect should be done to close this issue?

**Comment by olt** [comment]
I missed the reference to this issue. This can be closed.
Thanks!
