### ISSUE TITLE
mapproxy-seed not updated

### ISSUE THREAD

**Issue by FatherOSam** [mapproxy/mapproxy#318]
## Context

This is result after I have modified the mapproxy-seed requirements and comment out hte requirements line.
There appears to be another file that has version mismatch after upgrade

## Steps to Reproduce

As mentioned above upgrade from 1.9 to 1.10 via pip on CENTOS

## Your Environment

* Version used:
* Python 2.7
* Centos generic latest - VMWare

**Comment by olt** [comment]
Please provide more details about what you did (including output from the shell).

**Comment by FatherOSam** [comment]
# The upgrade was Via
"pip install --upgrade --no-deps MapProxy==1.10.0 --log log.txt"
excerpt from the log 
Installing collected packages: MapProxy
  Found existing installation: MapProxy 1.9.1
    Uninstalling MapProxy-1.9.1:
      Removing file or directory /usr/bin/mapproxy-seed
      Removing file or directory /usr/bin/mapproxy-util
      Removing file or directory /usr/lib/python2.7/site-packages/MapProxy-1.9.1-py2.7-nspkg.pth ...
...
      Removing file or directory /usr/lib/python2.7/site-packages/mapproxy/wsgiapp.pyc
      Successfully uninstalled MapProxy-1.9.1

Successfully installed MapProxy-1.10.0
Cleaning up...
You are using pip version 8.1.2, however version 9.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

**Comment by FatherOSam** [comment]
closed - the script was written by an inhouse admin, without updating the doco.
 Sorry for bothering you
