### ISSUE TITLE
Compact Cache Defrag Not Fully Functional In Certain Cases

### ISSUE THREAD

**Issue by FilmCoder** [mapproxy/mapproxy#327]
Does not work at all on Windows, or when fully cleaning a Compact Cache (all coverage and zoom levels).

It is not functional in these cases:
1. On Windows.  Consider this code in defrag.py:

```
        os.rename(tmp_bundle + '.bundle', bundle_file)
        if os.path.exists(tmp_bundle + '.bundlx'):
            os.rename(tmp_bundle + '.bundlx', bundle_file[:-1] + 'x')
        os.unlink(tmp_bundle + '.lck')
```

On Linux this is fine, because os.rename will replace the existing bundle file if there is one.  However on Windows, os.rename will raise an error if bundle_file already exists (which it will).  So os.remove(bundle_file) is required beforehand.

2. What if you clean the ENTIRE cache.  Then, no tmp_defrag bundle file will be created as defb.store_tiles in the below code will never be hit (which means a tmp bundle file won't be created).

```
        for y in range(128):
            tiles = [Tile((x, y, 0)) for x in range(128)]
            b.load_tiles(tiles)
            tiles = [t for t in tiles if t.source]
            if tiles:
                defb.store_tiles(tiles)
```

Then, when os.rename is called to move the defraged bundle file over (which won't exist) an error will be thrown.  In this situation, if no tiles are found, then the pertinent bundle file in the cache should be deleted as all tiles in it were found to be fraged.

**Comment by FilmCoder** [comment]
This should work:

```
        for y in range(128):
            tiles = [Tile((x, y, 0)) for x in range(128)]
            b.load_tiles(tiles)
            tiles = [t for t in tiles if t.source]
            if tiles:
                defb.store_tiles(tiles)

        # necessary on windows, to ensure the bundle files to be replaced are removed
        if os.path.exists(bundle_file):
            os.remove(bundle_file)
            os.remove(bundle_file[:-1] + 'x')

        if os.path.exists(tmp_bundle + '.bundle'):
            os.rename(tmp_bundle + '.bundle', bundle_file)
            if os.path.exists(tmp_bundle + '.bundlx'):
                os.rename(tmp_bundle + '.bundlx', bundle_file[:-1] + 'x')
            os.remove(tmp_bundle + '.lck')
```

**Comment by olt** [comment]
Should be fixed with the two recent commits.

**Comment by FilmCoder** [comment]
@olt Actually, the bundle and bundlex files should be removed regardless of the operating system, because of this edge case bug:

Suppose someone initiates a "clean" for ALL tiles in the cache, then calls defrag.  The store_tiles(tiles) function will never be called, meaning no tmp_bundle files will be created.  This leads to the original bundle files staying in the cache, even when the cache has been cleaned of all tiles.

**Comment by FilmCoder** [comment]
If we only attempt to remove the old bundle files when store_tiles is true, then the bug as note in the previous comment can occur.

**Comment by FilmCoder** [comment]
@olt issue should be reopened
