### ISSUE TITLE
Correction for "Installation on OSGeo4W" instructions

### ISSUE THREAD

**Issue by zstadler** [mapproxy/mapproxy#328]
## Context

As a result of the existing instruction text I was following the [Installation on OSGeo4W](https://mapproxy.org/docs/latest/install_osgeo4w.html) instructions. At the appropriate step, I was expected to download `distribute-setup.py` and run it with
```
C:\OSGeo4W> python C:\Users\MyUsername\Downloads\distribute-setup.py
```
## Expected Behavior

The `distribute-setup.py` python script should have been downloaded to `C:\Users\MyUsername\Downloads\` and executing it would have `easy_install` working.
## Actual Behavior

I was unable to find the source for downloading the `distribute-setup.py` python script. As a result I could not continue with the installation instructions.

Although the installation instructions include a link to [install the distribute package](http://pypi.python.org/pypi/distribute#distribute-setup-py), the `distribute-setup.py` script cannot be found there either.

## Possible Fix
 
The installation instructions can use following text

>  As happens with the standard Windows installation, you need to [install pip with get-pip.py](https://pip.pypa.io/en/stable/installing/#installing-with-get-pip-py) to get the easy_install command. 

instead of the text that starts with
> As happens with the standard Windows installation

upto and **NOT** including the text that starts with

> Once `easy_install ` is working within the OSGeo4W python environment

## Steps to Reproduce

1. Install [OSGeo4W](http://trac.osgeo.org/osgeo4w/).
2. Follow the [Installation on OSGeo4W](https://mapproxy.org/docs/latest/install_osgeo4w.html) instructions.

## Context

As a result of the existing instructions, I was unable to install MapProxy on OSGeo4W

## Your Environment

* Version used: installation instructions "Last updated on 2017-05-18"
* Operating System and version: Windows 10 Home, version 1709, OS Build 16296.0

**Comment by learning4life** [comment]
This updated instruction to the OSGeo4W installation is very welcome, as I also gave up on it.

I found the following solution very easy to implement on a Windows Server 2016:
https://github.com/baasgeo/mapproxywindows
