### ISSUE TITLE
arcgiscache_path Error (404): "Not found"

### ISSUE THREAD

**Issue by lzxue** [mapproxy/mapproxy#331]
I Have a  arcgiscache image service ,use the mappoxy to WMS servise.

1. the yaml config is right 
2. mapproxy request the orgin url also right 
3. the origin arcgis cache also  exist the resource 。
   but  it errored   it can‘t found the image

## the mapproxy logs like this
  
      Error "http://192.168.50.54:8082/L06/R00000017/C00000030.png')": 404
    [info] 172.17.0.1 - - [17/Oct/2017 05:40:07] "GET /service?LAYERS=arcgis&FORMAT=image%2Fpng&SRS=EPSG%3A3857&TRANSPARENT=TRUE&SERVICE=WMS&VERSION=1.1.1&REQUEST=GetMap&STYLES=&BBOX=10018754.17139462,5009377.085697312,10644926.307106785,5635549.221409474&WIDTH=256&HEIGHT=256 HTTP/1.1" 200 -

 ##  the arcgiscache map service logs  likes this. 

      [Tue Oct 17 2017 13:40:07 GMT+0800 (CST)] "GET /L06/R00000017/C00000030.png')" 
    "MapProxy-1.10.4"
     [Tue Oct 17 2017 13:40:07 GMT+0800 (CST)] "GET /L06/R00000017/C00000030.png')" Error 
      (404): "Not found"

 ##### in fact the  /L06/R00000017/C00000030.png   is exist  why not found

**Comment by olt** [comment]
There is a ``')`` at the and of the request, probably from your configuration?

Please reopen the issue if you still think this is a bug in MapProxy and provide a configuration and test requests (see comments in the text field of a "New Issue").
