### ISSUE TITLE
WMS service on_source_errors='raise' not behaving correctly

### ISSUE THREAD

**Issue by jdgarrett** [mapproxy/mapproxy#335]
## Context
Using MapProxyApp with a configured WMS service with 'on_source_errors' set to 'raise'.

## Expected Behavior
A source error should result in an OGC service exception.

## Actual Behavior
An image is returned with an error message rendered onto it and a 200 status code.

## Possible Fix
After doing some digging, there is an attribute on mapproxy.request.wms.WMSMapRequest called 'prevent_image_exception' that is set to False.  I haven't been able to find a way to set this to True from the client.  I tried supplying an alternate request_parser in the service config that would override the attribute after the request was created, but found that it is not passed on to the WMSServer when the configuration is loaded.

## Steps to Reproduce
1. Configure a WMS service with 'on_source_errors' set to 'raise'.
2. Disconnect MapProxy from the source.
3. Issue a request to get a map image.
4. See the error rendered in the image.

**Comment by olt** [comment]
``on_source_errors`` configures what should happen if there are multiple sources in a request and only one fails. It does not change the behavior _how_ the error is returned.

The client decides if an error should be returned in the image or as an XML document with the WMS ``exception`` parameter.

**Comment by jdgarrett** [comment]
Hmm, that's why I gathered from looking at the code, but I wasn't sure because the documentation about the option is a bit ambiguous.  Is there any documentation for the `exception` parameter?  I haven't seen it while investigating this issue.

**Comment by olt** [comment]
Please post an example requests.
The parameter os part of the OGC WMS specification: EXCEPTIONS=INIMAGE and EXCEPTIONS=XML

**Comment by jdgarrett** [comment]
Ah, I think I see the issue now.  `/service?LAYERS=layerName&FORMAT=image/png&SRS=ESPG:4326&EXCEPTIONS=application/vnd.ogc.se_xml&TRANSPARENT=TRUE&SERVICE=WMS&VERSION=1.1.1&REQUEST=GetMap&STYLES=&BBOX=-180.0,-90.0,180.0,90.0&WIDTH=256&HEIGHT=256` returns the OGC exception as base64 encoded XML, but with a 200 status code and `img/png` content-type header.  Is that the intended behavior?

**Comment by jdgarrett** [comment]
Turns out the issue was with how the response was behind handled on my end.  Thanks for the help!

**Comment by olt** [comment]
200 is the *right* status code according to the OGC, but you should get ``application/vnd.ogc.se_xml`` as the content type...

**Comment by jdgarrett** [comment]
Yeah, the application I was debugging was using the MapProxyApp.__call__ method and getting only the response content back (it doesn't return the full Response object).  So the application code was wrapping that response content in another Response that had the png content type.
