### ISSUE TITLE
Problems with header strings when serving mapproxy in waitress server

### ISSUE THREAD

**Issue by simonseyock** [mapproxy/mapproxy#382]
## Context

I tried to serve mapproxy with the [waitress wsgi server](https://docs.pylonsproject.org/projects/waitress/en/latest/) on windows. This webserver is quite useful because it is relatively platform independent. I ran into an issue though with header string type.

## Expected Behavior vs Actual Behavior
The waitress server requires the header value to be standard str type. See https://github.com/Pylons/waitress/blob/master/waitress/task.py#L428
In mapproxy the header value is (sometimes) a subtype of str i.e. ImageFormat. This is not recognized by waitress.
In the wsgi standard it is said that strings have to be of type str https://www.python.org/dev/peps/pep-3333/#a-note-on-string-types . So I would assume this is rather a problem of mapproxy than of waitress. But on the other hand you could say a subtype of str is a str. I don't know exactly. I can file a bug at the waitress repository as well.

## Possible Fix
convert str subtypes to str before passing them to the wsgi server.

## Steps to Reproduce

1. Configure a mapproxy with a wms
1. mapproxy-util create -t wsgi-app -f mapproxy.yaml config.py
2. waitress-serve --listen=*:3000 config:application
3. Try to get an image from the wms

## Your Environment
python: 3.6
mapproxy: 1.11.0
waitress: 1.1.0

**Comment by olt** [comment]
Can you try with the latest master? I think this has been fixed with https://github.com/mapproxy/mapproxy/commit/1e61d41164c286cd3ff94234bb9d4f6fd5442cc8

**Comment by simonseyock** [comment]
That looks pretty much like the problem! I will look into this later, thank you very much.

**Comment by simonseyock** [comment]
Using master does do the trick. Thanks.
