### ISSUE TITLE
Couldn't find any package whose name or description matched "libproj0"

### ISSUE THREAD

**Issue by yh371174229** [mapproxy/mapproxy#389]
no matter i use apt install or aptitude install,it tells me can't find package  libproj0
![image](https://user-images.githubusercontent.com/5948456/50536571-b74d3f80-0b90-11e9-9349-8b203df8dd41.png)

**Comment by yh371174229** [comment]
https://mapproxy.org/docs/1.11.0/install.html
Is it a mistake??

**Comment by Niarolf** [comment]
Hi,
Have you try to find another similar library with the command "apt cache
search libproj" ?

Le sam. 29 déc. 2018 à 10:41, YoungHappy <notifications@github.com> a
écrit :

**Comment by yh371174229** [comment]
![image](https://user-images.githubusercontent.com/5948456/50578058-12bc4d80-0e6f-11e9-9110-62ac23a3fca6.png)

Thanks for helping，I find it。
