### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by micw** [mapproxy/mapproxy#394]
Hello,
I have seen that there is effort on making mapproxy work on recent python versions in the current master since release 1.11.0. Most auto-build docker images does not work anymore since the base images switched to newer python. Could you please create a new release?

Kind regards,
Michael Wyraz.

**Comment by mprins** [comment]
please close, a new release (1.12.0) was published on 2019-08-30
https://mapproxy.org/blog/new-mapproxy-1.12.0-release/

**Comment by weskamm** [comment]
well, the master works on python 3.8 but the latest release 1.12 does not, so this is still a valid issue which will be handled soon

**Comment by weskamm** [comment]
as 1.13 has been released, i am closing this now
