### ISSUE TITLE
async and pyproj issues with Python 3.7 on Windows10

### ISSUE THREAD

**Issue by rduivenvoorde** [mapproxy/mapproxy#417]
## Context

Reinstalling Mapproxy on a fresh Windows10 64 bit server, Apache2 and mod_wsgi (coming from an old Windows Server 2008 32 bits install....).

Encountered 2 issues, one I cannot resolve:

1) issues that apparently async is a keyword in Python 3.7, so renaming mapproxy.util.asyc.py to async_.py (and all its references like as in https://gitlab.damiens.info/nicolas/mapproxy/commit/ee5c9589274610e43e34f31ac067e949531d9d8e) fixed that error

2) installing pyproj and using os.environ['MAPPROXY_USE_PYPROJ'] = 'True' in config.py to make MapProxy use pyproj fails, because try_pyproj_import function seems to fail

```
 def try_pyproj_import():
    try:
        from pyproj import Proj, transform, set_datapath
    except ImportError:
        return False
    log_system.info('using pyproj for coordinate transformation')
    return Proj, transform, set_datapath
```

installing pyproj and running

` from pyproj import Proj, transform, set_datapath`

fails because set_datapath is not available:

`ImportError: cannot import name 'set_datapath' from 'pyproj' (C:\Programs\Python37\lib\site-packages\pyproj\__init__.py)`

downgrading to pyproj 1.9.6 fixed this:

`pip install pyproj==1.9.6`

Is this something that can be fixed easily (other then with using the older pyproj)?

**Comment by Rakesh4G** [comment]
We have also faced this issue. We are trying to use Mapproxy on NixOS. 
https://github.com/NixOS/nixpkgs/pull/68628

But It breaks with same errors, when latest version of pyproj is used.

**Comment by olt** [comment]
MapProxy now supports newer versions of Proj via PyProj. You can test it with:

    pip install https://github.com/mapproxy/mapproxy/tarball/master

The async.py issue is also fixed in master.

**Comment by kalxas** [comment]
Thanks for the fix @olt 
Any chance for a 1.13 release soon to support latest PROJ versions?
