### ISSUE TITLE
Unormal speed of reseeding of WMS geoserver source

### ISSUE THREAD

**Issue by tyomik-mnemonic** [mapproxy/mapproxy#423]
I face a unormal speed of re- seeding (updating old tiles by new from one source - WMS Geosrver (in geoserver this data taken from postgres source)) from 5.32% to this [08:39:10] 11   5.42% -10175297.20532, 13149614.84996, -10018754.17139, 13306157.88388 (27568 tiles) reseeding works for about 8 hours! We use CentOS, 16 gb ram , ssd. When seeding was running console throws this information: Limited to coverage in: -180.00000, -85.05113, 180.00000, 85.05113 (EPSG:4326) it is ok? all my data in 3857, and I tried use coverage for 3857 , but when seeding is start I see 4326 again..
What be the reason of so slowly working (reseeding)?

## Expected Behavior
A initial seeding was faster: World coverage with different difficulty of style From 0 to 12 zoom level was cached by about 30 hours

## Actual Behavior
Re seeding now is so slowly, about 0.1 % per 8-10 hours..

## Your Environment
CentOS , 16gb ram, ssd
Environment name and version Python 2.7.5 
MapProxy 12
Geoserver 15.2

**Comment by weskamm** [comment]
This heavily depends on your configuration and i doubt its an issue of mapproxy.

The limiting coverage you mention above is nearly the whole world. Depending on the count and value of your resolutions you use for your grid, which i dont know, this may last from 1 minute to infinite years.

I will close this issue now, feel free to reopen with detailed information about your configuration if the issue still persists.
