### ISSUE TITLE
mapproxy-util is being executed as a python script

### ISSUE THREAD

**Issue by CMCDragonkai** [mapproxy/mapproxy#424]
Hi, we are packaging mapproxy for NixOS: https://github.com/NixOS/nixpkgs/pull/68628. And we have hit some problems.

The main problem is that Nix will wrap executables as shell scripts in order to create an isolated environment. Once we execute `mapproxy-util serve-develop mapproxy.yaml` we get a syntax error.

```
»» ~/Projects/mapproxy/mymapproxy
 ♖ ../result/bin/mapproxy-util serve-develop mapproxy.yaml
[2019-10-02 13:22:18,621] mapproxy.config - INFO - reading: /home/cmcdragonkai/Projects/mapproxy/mymapproxy/mapproxy.yaml
[info]  * Running on http://127.0.0.1:8080/ (Press CTRL+C to quit)
[info]  * Restarting with reloader
  File "/nix/store/bfvw32p8c61jajjm7a8z98xbk1n6qiwz-python3.7-MapProxy-1.12.0/bin/mapproxy-util", line 2
    export PATH='/nix/store/kimimvhimclyfzlncpg36zjni3wn70nq-python3-3.7.3/bin:/nix/store/bfvw32p8c61jajjm7a8z98xbk1n6qiwz-python3.7-MapProxy-1.12.0/bin:/nix/store/rpayih9fb4ms2wjvmyn6kp7kmsizim49-python3.7-setuptools-40.8.0/bin:/nix/store/kp0g7z5h4kr6gx71jf9q0a9322p4jr5p-python3.7-numpy-1.16.2/bin:/nix/store/7vgnq00rxw9xh03920apdyj4ibgsmrix-gdal-2.4.0/bin'${PATH:+':'}$PATH
              ^
SyntaxError: invalid syntax
```

I suspect that this is occurring because mapproxy thinkgs that `mapproxy-util` is a python script. And from Nix's perspective these are arbitrary executables. So they should just be executed like any other executable without needing to call it again from `python`.

What we would do in Nixpkgs is to basically hotpatch the package so that it doesn't bother trying to call the script as a python script. This is similar to what we had to do for dvc:  https://github.com/NixOS/nixpkgs/pull/54530/files#diff-551883c582fc9bc6f5388f662439af05

What I'd like to know is where your this patch is best applied? Where exactly in the program are you recalling `mapproxy-util` script like a Python script.

**Comment by Rakesh4G** [comment]
Hi all, 
This issue seems to be fixed we add the following change in **mapproxy/util/ext/serving.py**.
replace **"args = [sys.executable] + sys.argv"**  with
**"args = sys.argv"**

**Comment by olt** [comment]
This likely will break the reloading on other systems.

**Comment by CMCDragonkai** [comment]
That can be a Nixpkgs specific patch.

On 28 November 2019 13:53:55 GMT+08:00, Rakesh Gupta <notifications@github.com> wrote:
>Hi all, 
>This issue seems to be fixed we add the following change in
>**mapproxy/util/ext/serving.py**.
>replace **"args = [sys.executable] + sys.argv"**  with
>**"args = sys.argv"**
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/mapproxy/mapproxy/issues/424#issuecomment-559352663

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by CMCDragonkai** [comment]
Looks like this is done for Nixpkgs.
