### ISSUE TITLE
Mapproxy not connecting via http_proxy

### ISSUE THREAD

**Issue by WakandaKing** [mapproxy/mapproxy#428]
i want to configure my Mapproxy to connect to extenral sources via http proxy, I have configured the http proxy in the environment variables of my linux host but it seems like Mapproxy does not 
 use the environmental variables to connect through the http proxy?

Is there any other configuration that has to be done to  make this work?

**Comment by Niarolf** [comment]
Hi,
Where have you configure http_proxy and what is your installation ?
For me with apache2 on debian, in installation it's in /etc/apache2/envvars with http_proxy="http://X.X.X.X:XX"
Regards

**Comment by WakandaKing** [comment]
The http_proxy and Mapproxy are running on two separate linux machines, I did set the environmental variables on the machine running MapProxy as below.

" export http_proxy="http://example.com:3128" https_proxy="http://example.com:3128"

**Comment by Niarolf** [comment]
Wich web server do you have ?
Be carefull to affect the variable for the web server user ans restart the service.

**Comment by weskamm** [comment]
There is no proxy configuration inside mapproxy, you have to set it on the system that runs mapproxy / the webserver that serves mapproxy.
I can tell that it works when configured correctly.
