### ISSUE TITLE
BaseURL in Capabilities

### ISSUE THREAD

**Issue by bloigge** [mapproxy/mapproxy#451]
We are using a mapproxy instance behind a HTTPS NGINX reverse proxy. Is it possible to change the BaseUrl in the ResourceURL for the Layers in the Capabilities documents so it points to the reverse proxy? 

In geoserver for example this can be changed using the Proxy Base URL global setting .

**Comment by olt** [comment]
See https://mapproxy.org/docs/nightly/deployment.html#http-proxy
