### ISSUE TITLE
Python 3.8 compatibility

### ISSUE THREAD

**Issue by Raviu56** [mapproxy/mapproxy#462]
## Context
On Ubuntu 20.4 with python 3.8 .. mapproxy 1.12 cannot work fine without some modifications

## Expected Behavior
It should simply work

## Actual Behavior
errors like this:
```
AttributeError: module 'cgi' has no attribute 'parse_qsl'
ImportError: cannot import name 'escape' from 'cgi' (/usr/lib/python3.8/cgi.py)
```

## Possible Fix
According to
https://stackoverflow.com/a/58871055
I've modified the cgi.escape to html.escape cgi.parse_qsl to urllib.parse.parse_qsl
It's working now

## Your Environment
* Version used: MapProxy==1.12.0 from apt python3-mapproxy package
* Environment name and version: Python 3.8.2
* Server type and version: server-develop with some testing configs
* Operating System and version: Ubuntu 20.04 LTS

**Comment by Raviu56** [comment]
This should be a fix for 1.12 not a new version I think, so as it's updated on Ubuntu LTS  packages too.

**Comment by tobwen** [comment]
This one will appear on a weekly level now... https://github.com/mapproxy/mapproxy/issues/458

**Comment by martijn-heil** [comment]
It appears this proper *compat* handling is actually [already implemented](https://github.com/mapproxy/mapproxy/blob/master/mapproxy/compat/modules.py), it seems we just need to change the parts of the code mentioned i this thread to use it.

**Comment by martijn-heil** [comment]
I think I've fixed it [on my freshly forked branch](https://github.com/martijn-heil/mapproxy/commit/2c75feb40d6c2704ea385cabffb03c6ffe5e4b75). Haven't tested it yet, when I'm done I'll make a pull request.

**Comment by martijn-heil** [comment]
Still haven't tested it but I've made pull request #468
