### ISSUE TITLE
upgrade PROJ4 to PROJ6.X -> Python 3.8.X compatibility

### ISSUE THREAD

**Issue by andreassteiner97** [mapproxy/mapproxy#469]
When installing mapproxy I tried to install it along with Python 3.8.5. 
This didn't work because PYPROJ 1.9.6 is only working with <= Python 3.7.X. 

The solution for that would be to implement a newer version of PROJ. 

![image](https://user-images.githubusercontent.com/59861665/89623750-76053180-d895-11ea-80b4-0a2f2206ee47.png)
--> https://pyproj4.github.io/pyproj/stable/installation.html

Then everyone could install the newest version of python + mapproxy.

**Comment by olt** [comment]
MapProxy now supports newer versions of Proj via PyProj. You can test it with:

    pip install https://github.com/mapproxy/mapproxy/tarball/master
