### ISSUE TITLE
travis-ci.org migration

### ISSUE THREAD

**Issue by olt** [mapproxy/mapproxy#487]
travis-ci.org forces all users to migrate to travis-ci.com. There is still a free plan on the .com version of Travis, but it has a limited number of "credits" and it is not sure (for me) what happens if the credits are all used.

@mapproxy/psc does anyone know what implication the migration to .com has? Are there any good alternatives with an easy migration path?

**Comment by weskamm** [comment]
What about github actions ? https://github.com/mapproxy/mapproxy/actions/new

**Comment by ramunasd** [comment]
+1 for github actions, quite stable and fast, easy integration

**Comment by justb4** [comment]
+1 GH Actions.

**Comment by weskamm** [comment]
fixed by https://github.com/mapproxy/mapproxy/pull/534
