### ISSUE TITLE
No handlers could be found for logger "mapproxy.system"

### ISSUE THREAD

**Issue by drnextgis** [mapproxy/mapproxy#499]
According to the [docs](https://mapproxy.org/docs/nightly/deployment.html#enabling-logging):

> The test server is already configured to log all messages to the console (stdout).

But since version 1.13.0 you can see the following error message while running test server:

```
$ mapproxy-util --help                                                
No handlers could be found for logger "mapproxy.system"
```

This error comes from [here](https://github.com/mapproxy/mapproxy/blob/3a5d3844faa90065c50110edccaa53c34644c998/mapproxy/script/util.py#L28) because the import is done before `setup_logging()` call:

```
>>> from mapproxy.script.conf.app import config_command
No handlers could be found for logger "mapproxy.system"
```

If trace the chain of calls, you can see that the error occurs in `mapproxy/proj.py` module:

```
>>> import mapproxy.proj
No handlers could be found for logger "mapproxy.system"
```

System info:

```
$ python --version
Python 2.7.17

$ pip freeze      
MapProxy==1.13.0
Pillow==6.2.2
PyYAML==5.4.1
Shapely==1.7.1
```

It is Python 2 only issue:

```
$ python
Python 2.7.17 (default, Sep 30 2020, 13:38:04) 
[GCC 7.5.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import logging
>>> log = logging.getLogger('mapproxy.system')
>>> log.warn('warning')
No handlers could be found for logger "mapproxy.system"
```
```
$ python3            
Python 3.6.9 (default, Oct  8 2020, 12:12:24) 
[GCC 8.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import logging
>>> log = logging.getLogger('mapproxy.system')
>>> log.warn('warning')
warning
```

**Comment by weskamm** [comment]
this should be resolved as python 2 support has been removed
