### ISSUE TITLE
Get legend graphic in json format

### ISSUE THREAD

**Issue by stijn-at-work** [mapproxy/mapproxy#540]
I am trying to get the legend graphic in json format via Mapproxy.

## Context

Cannot fetch legend graphic in application/json format using mapproxy. The following request returns 'internal error'.

http://localhost:8080/service?service=WMS&request=GetLegendGraphic&format=application/json&width=20&height=20&layer=[name]&style=[name]&VERSION=1.3.0&SLD_VERSION=1.1.0&TRANSPARENT=true

I can get the image/png version of the legend using mapproxy. The server returns the image. 

http://localhost:8080/service?service=WMS&request=GetLegendGraphic&format=image/png&width=20&height=20&layer=[name]&style=[name]&VERSION=1.3.0&SLD_VERSION=1.1.0&TRANSPARENT=true

I can also get the application/json when i make a request to the source directly, without Mapproxy. The geoserver returns json.

https://geo.[site].nl/geoserver/[subdomain]/wms?service=WMS&request=GetLegendGraphic&format=application/json&legendgraphic=true&version=1.3.0&featureinfo=true&layer=[layer].

## Expected Behavior

Return json

## Actual Behavior

Internal error.

## Possible Fix

Is there a configuration option? I did not find one in the docs. 

## Your Environment

* Version used: MapProxy 1.13.2
* Operating System and version: MacOs Big Sur

**Comment by stijn-at-work** [comment]
i have copied the querystring of my geoserver request and used it in my MapProxy request. it (still) works for an image format, but not for json response.

json request still returns 'internal error':
http://localhost:8080/wms?service=WMS&request=GetLegendGraphic&format=application/json&legendgraphic=true&version=1.3.0&featureinfo=true&layer=[layer]

image request still returns 200 OK with legend:
http://localhost:8080/wms?service=WMS&request=GetLegendGraphic&format=image/png&legendgraphic=true&version=1.3.0&featureinfo=true&layer=[layer]

**Comment by stijn-at-work** [comment]
The logs provide a hint where the code breaks. 

KeyError: 'application/json'

request log:

[info] 127.0.0.1 - - [15/Oct/2021 18:43:15] "GET /wms?service=WMS&request=GetLegendGraphic&version=1.3.0&layer=[layer]&format=application/json HTTP/1.1" 500 -
[2021-10-15 18:48:32,279] mapproxy.wsgiapp - CRITICAL - fatal error in wms for /wms?service=WMS&request=GetLegendGraphic&version=1.3.0&layer=[layer]&format=application/json
Traceback (most recent call last):
  File "/[user]/mapproxy/lib/python3.9/site-packages/mapproxy/wsgiapp.py", line 141, in __call__
    resp = self.handlers[handler_name].handle(req)
  File "/[user]/mapproxy/lib/python3.9/site-packages/mapproxy/service/ows.py", line 38, in handle
    return self.services[service].handle(req)
  File "/[user]/mapproxy/lib/python3.9/site-packages/mapproxy/service/base.py", line 30, in handle
    return handler(parsed_req)
  File "/[user]/mapproxy/lib/python3.9/site-packages/mapproxy/service/wms.py", line 315, in legendgraphic
    img_opts = self.image_formats[request.params.format_mime_type]
KeyError: 'application/json'
Traceback (most recent call last):
  File "/[user]/mapproxy/lib/python3.9/site-packages/mapproxy/wsgiapp.py", line 141, in __call__
    resp = self.handlers[handler_name].handle(req)
  File "/[user]/mapproxy/lib/python3.9/site-packages/mapproxy/service/ows.py", line 38, in handle
    return self.services[service].handle(req)
  File "/Users/stijnblommerde/mapproxy/lib/python3.9/site-packages/mapproxy/service/base.py", line 30, in handle
    return handler(parsed_req)
  File "/Users/stijnblommerde/mapproxy/lib/python3.9/site-packages/mapproxy/service/wms.py", line 315, in legendgraphic
    img_opts = self.image_formats[request.params.format_mime_type]
KeyError: 'application/json'
[info] 127.0.0.1 - - [15/Oct/2021 18:48:32] "GET /wms?service=WMS&request=GetLegendGraphic&version=1.3.0&layer=[layer]&format=application/json HTTP/1.1" 500 -

**Comment by weskamm** [comment]
Maybe you can try to setup a PullRequest that fixes the issue, since it seems you already found the problematic code?
I can of course assist if you have problems.

**Comment by stijn-at-work** [comment]
I am trying to update the python code and have some questions. Can i contact you by email? My email: stijn@apptimize.nl

**Comment by drnextgis** [comment]
@stijn-at-work just ask it in this thread.

**Comment by stijn-at-work** [comment]
i have create a draft pull request and named it 'request legend in json format'

**Comment by stijn-at-work** [comment]
I have finished the pull request, including a system test, and marked it as ready for review. Can someone review the code? Thanks
