### ISSUE TITLE
Python 3.9: No such file or directory: b'liblibgdal.a'

### ISSUE THREAD

**Issue by tobwen** [mapproxy/mapproxy#558]
## Context
`load_ogr_datasource` can't be used, since `find_library()` throws `OSError FileNotFoundError`.

## Expected Behavior
Locate and load `libgdal.a`

## Actual Behavior
``` python
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.9/ctypes/util.py", line 341, in find_library
    _get_soname(_findLib_gcc(name)) or _get_soname(_findLib_ld(name))
  File "/usr/lib/python3.9/ctypes/util.py", line 147, in _findLib_gcc
    if not _is_elf(file):
  File "/usr/lib/python3.9/ctypes/util.py", line 99, in _is_elf
    with open(filename, 'br') as thefile:
FileNotFoundError: [Errno 2] No such file or directory: b'liblibgdal.a'
```
## Analysis
According to this WONTFIX,  adding _lib_ prefix to any library has always been wrong and rises an exception: https://bugs.python.org/issue42580

`libgdal.a` is located where it is expected to be:
``` bash
$ whereis libgdal.a
libgdal: /usr/lib/libgdal.a /usr/lib/libgdal.so
```

Importing `ogr` works as expected:
``` python
from osgeo import ogr
```

## Possible Fix
https://github.com/mapproxy/mapproxy/blob/655adafd6b42f1e12bf123ebc52498269007c323/mapproxy/util/lib.py#L92-L96

### backward compatible fix
``` python
    if not paths or not exts:
        try:
            lib = _find_library(lib_name)
        except OSError:
            if lib_name.startswith('lib'):
                lib = _find_library(lib_name[3:])
        return lib
```

### easiest workaround: environment variable
This environment variable makes use of `from osgeo import ogr`
``` sh
MAPPROXY_USE_OSGEOOGR=1 python3 mapproxy-issue-558.py
```

### really evil workaround (last resort)
``` sh
sudo ln -s -f /usr/lib/libgdal.a /usr/lib/liblibgdal.a
```

## Steps to Reproduce
(inside venv)
1. `pip install git+https://github.com/mapproxy/mapproxy/`
2. `pip install shapely pygdal=3.2.2.*`
3. `python3 mapproxy-issue-558.py`

## Context
I'm loading coverages using this code:
``` python
import glob
import gc
from mapproxy.util.geom import (
    load_datasource,
    load_ogr_datasource,
    load_polygons,
    require_geom_support,
    build_multipolygon,
)

path  = '/home/tobwen/mapproxy/masks/'
ext   = 'geojson'

areas = {}
for filepath in glob.iglob(f'{path}/*.{ext}', recursive=True):
    bbox, geom = build_multipolygon(load_ogr_datasource(filepath), simplify=False)
    area = filepath[len(path)+1:][:-len(ext)-1]
    areas[area] = geom
del area, bbox, geom
gc.collect()
```

## Your Environment
* Version used: MapProxy 1.14.0.post20211221
* Environment name and version (e.g. Python 2.7.5 with mod_wsgi 4.5.9): Python 3.9.2, pygdal 3.2.2.10, gdal 3.2.2+dfsg-2+deb11u1 
* Server type and version: VPS
* Operating System and version: Debian Bullseye, 64 bit, latest release

**Comment by tudorbarascu** [comment]
You can do a workaround and do a symbolic link so that /usr/lib/liblibgdal.a points to 
/usr/lib/libgdal.a. 

something like ``sudo ln -s /usr/lib/libgdal.a /usr/lib/liblibgdal.a`` should work

**Comment by tobwen** [comment]
> You can do a workaround and do a symbolic link

Yeah, see my workarounds. But this is very, very evil.

**Comment by weskamm** [comment]
should be fixed by https://github.com/mapproxy/mapproxy/pull/617
