### ISSUE TITLE
Get different projections from WMTS 

### ISSUE THREAD

**Issue by mahdiZghi** [mapproxy/mapproxy#587]
Hello everyone,

I am trying to setup MapProxy's WMTS service in such a way, that the received tile image is projected in a different SRS than the request's SRS. For example, I would like to be able to provide the TileRow and TileColumn in EPSG:900913 and get the tile projected in UTM32 (EPSG:32632). Would that be possible?

**Comment by weskamm** [comment]
please use the mailinglist for questions
