### ISSUE TITLE
[feature request] Update Openlayers in demo

### ISSUE THREAD

**Issue by fatuuse** [mapproxy/mapproxy#588]
## Context
Old version of OpenLayers in demo with no mobile support pinch to zoom etc.

## Your Environment
* Version used: 1.15.1
* Environment name and version (e.g. Python 2.7.5 with mod_wsgi 4.5.9): python 3.10.4.  alpine build
* Operating System and version: in Docker container

**Comment by weskamm** [comment]
This is handled in https://github.com/mapproxy/mapproxy/pull/616
