### ISSUE TITLE
refresh_before not working anymore

### ISSUE THREAD

**Issue by tobias-brunner** [mapproxy/mapproxy#625]
Just upgraded to mapproxy 1.15.1 and now the refresh_before (minutes: 1) parameter has no effect during seeding anymore (sqlite). No tiles are recreated. If a cache does not exist, then seeding works perfectly.

After reverting to 1.14 it's working again.

running on Windows Server. Python 3.9. Osgeo4w.

**Comment by weskamm** [comment]
Thanks for the report. This issue has already been fixed a while ago in the current master

https://github.com/mapproxy/mapproxy/commit/fef53b72b030587f9c0be4011295c6ece0256568T

but that fix is not released yet in a new version.
A new release happening soon has now become very likely
