### ISSUE TITLE
mapproxy-1.15.1  pip install also needs proj and six

### ISSUE THREAD

**Issue by gplanansky** [mapproxy/mapproxy#627]
Bug:  after installing with vanilla ``pip install mapproxy``, ``mapproxy-util --version`` fails

Expected Behavior:  should just work

Steps to Reproduce:*

* $ virtualenv  venv-mp

* $ source venv-mp/bin/activate

* (venv-mp) $ pip list
Package    Version
\-----------------
pip        22.3.1
setuptools 65.7.0
wheel      0.38.4

* (venv-mp) $ pip install mapproxy
Collecting mapproxy
  Using cached MapProxy-1.15.1-py2.py3-none-any.whl (1.4 MB)
Collecting PyYAML>=3.0
  Using cached PyYAML-6.0-cp310-cp310-macosx_11_0_arm64.whl (173 kB)
Collecting Pillow!=2.4.0,!=8.3.0,!=8.3.1
  Downloading Pillow-9.4.0-cp310-cp310-macosx_11_0_arm64.whl (3.0 MB)
  3.0/3.0 MB 7.0 MB/s eta 0:00:00
Installing collected packages: PyYAML, Pillow, mapproxy
Successfully installed Pillow-9.4.0 PyYAML-6.0 mapproxy-1.15.1

* test
(venv-mp) $ mapproxy-util --version
Traceback (most recent call last):
  File "/opt/venv-mp/bin/mapproxy-util", line 5, in <module>
    from mapproxy.script.util import main
  File "/opt/venv-mp/lib/python3.10/site-packages/mapproxy/script/util.py", line 29, in <module>
    from mapproxy.script.conf.app import config_command
  File "/opt/venv-mp/lib/python3.10/site-packages/mapproxy/script/conf/app.py", line 32, in <module>
    from .sources import sources
  File "/opt/venv-mp/lib/python3.10/site-packages/mapproxy/script/conf/sources.py", line 17, in <module>
    from mapproxy.srs import SRS
  File "/opt/mp/venv-mp/lib/python3.10/site-packages/mapproxy/srs.py", line 26, in <module>
    from mapproxy.proj import USE_PROJ4_API
  File "/opt/venv-mp/lib/python3.10/site-packages/mapproxy/proj.py", line 289, in <module>
    raise ImportError('could not find pyproj (Python library) or libproj (C library, deprecated)')
ImportError: could not find pyproj (Python library) or libproj (C library, deprecated)

*  fix
  ``pip install pyproj`` then gets similar error with lack of ``six`` .
  After a further ``pip install six``, ``mapproxy-util --version`` successfully returns ``MapProxy 1.15.1``

Context:
* Installing mapproxy on macos 13.2 via pip,  as the linux tools ``apt`` etc. do not apply on macos.

Your Environment:  
* macos 13.2  arm64
* python 3.10.9  (also with 3.11)

**Comment by weskamm** [comment]
I think the six issue should be fixed by https://github.com/mapproxy/mapproxy/pull/604/files

Installing of pyproj should be handled by http://mapproxy.github.io/mapproxy/install.html#id1 whereas one would need to install python3-pyproj.

The documentation needs an update. will keep this open as a reminder.
Thanks for report!

**Comment by weskamm** [comment]
documentation updated, feel free to reopen this if there are still issues left
