### ISSUE TITLE
Add layer extent to WMTS Capabilities

### ISSUE THREAD

**Issue by asafMasa** [mapproxy/mapproxy#659]
## Context

each layer has 2 extents
* projection extent - example for 4326 - Bounds:  180.0000, -90.0000, 180.0000, 90.0000
* layer extent - actual layer Bounds:  13.9, 41, 15, 42

## Expected Behavior
Should be able to provide layer extent for WMTS layer (use case cache type: s3)

## Actual Behavior
unable to provide layer extent for WMTS layer (use case cache type: s3)

## Possible Fix
Add support for extent for WMTS layer

## Context

wmts capabilities should provide this data for clients so they won't request irrelevant tiles 

## Your Environment

* Version used: 1.16

**Comment by shimoncohen** [comment]
@weskamm I think this issue can be closed. Thank you very much!
