### ISSUE TITLE
order of services in WMTS is not maintained in contrast to WMS 

### ISSUE THREAD

**Issue by hannesaddec** [mapproxy/mapproxy#679]
## Context
Services are not appear in WMTS in the same order than in WMS  

## Expected Behavior
Services should appear in the same order in all endpoints (wmts/wms/tms)

## Actual Behavior
random python do to missing odict import 

## Possible Fix
The solution is to add one single line in those two files:

*/opt/data/mapproxy/lib/python2.7/site-packages/mapproxy/config/loader.py:* At "demo_service(self, conf)" function right before return statement:
 * {{layers = odict(sorted(layers.items(), key=lambda x: x[1].name))}}

*/opt/data/mapproxy/lib/python2.7/site-packages/mapproxy/service/demo.py* At "_render_template(self, template)" function right before return statement.
 * {{wmts_layers = odict(sorted(wmts_layers.items(), key=lambda x: x[0]))}}

 * Besides, in this case "odict" import statement needs to be added at the start of the file:
 ** {{from mapproxy.util.ext.odict import odict}}

## Steps to Reproduce
1.Create a series of layers (e.g. 200) with alphabetically ordered services 
2. load that configuration into mapproxy
3. check demo page

## Context
select a dedicated services based on an alphabetic (name/year) ordered combination

## Your Environment

* Version used: 
* Environment name and version (e.g. Python 2.7.5 with mod_wsgi 4.5.9): Python 2.7 
* Server type and version: 
* Operating System and version: Ubuntu

**Comment by weskamm** [comment]
as you have already found a fix, maybe you can create a pull request for the issue?

**Comment by hannesaddec** [comment]
PR will be prepared also fixing for TMS

**Comment by hannesaddec** [comment]
PR is submitted.
