### ISSUE TITLE
Update old documentation mapproxy.org/docs* to link to new documentation mapproxy.github.io/mapproxy

### ISSUE THREAD

**Issue by petersmythe** [mapproxy/mapproxy#685]
Is it possible to put a banner on all the pages on https://mapproxy.org/documentation (including https://mapproxy.org/docs*) to highlight the fact that this is old documentation and that the new documentation is available at https://mapproxy.github.io/mapproxy/ ?

For users who go directly to https://mapproxy.org, it is not obvious that there are later versions than v1.13.1

Or is that site no longer accessible for changes?

**Comment by hblitza** [comment]
It's on our list @terrestris (Homepage topic), I hope to solve this by end of next month. Thanks for reminding :pray:

**Comment by weskamm** [comment]
ping @hblitza

**Comment by kom177** [comment]
Any progress?

**Comment by weskamm** [comment]
@hblitza please remove the information regarding v2.0.0 from the documentation when you are qworking on it, the infos are outdated
http://mapproxy.github.io/mapproxy/mapproxy_2.html

**Comment by hblitza** [comment]
:bell: github workflow has been implemented. New docs are build and deployed when new tag is pushed. Also old docs are accessible at https://mapproxy.github.io/mapproxy   

The `docs` button on the homepage https://mapproxy.org now links to https://mapproxy.github.io/mapproxy. Search engines will need some time to update/remove old links (some already did update the search index).

**Comment by weskamm** [comment]
Seems like the issue is resolved
