### ISSUE TITLE
Unknown start tag in capabilities

### ISSUE THREAD

**Issue by karlis-vagalis** [mapproxy/mapproxy#820]
While trying to generate valid mapproxy configuration file by using `mapproxy-util autoconfig --capabilities` an issue:
```
unknown start tag in capabilities: {http://www.opengis.net/wmts/1.0}Capabilities
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/mapproxy/script/conf/app.py", line 140, in config_command
    cap = parse_capabilities(BytesIO(cap_doc))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/mapproxy/util/ext/wmsparse/parse.py", line 300, in parse_capabilities
    raise ValueError('unknown start tag in capabilities: ' + root_tag)
ValueError: unknown start tag in capabilities: {http://www.opengis.net/wmts/1.0}Capabilities

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/mapproxy-util", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/local/lib/python3.11/site-packages/mapproxy/script/util.py", line 403, in main
    commands[command]['func'](args)
  File "/usr/local/lib/python3.11/site-packages/mapproxy/script/conf/app.py", line 143, in config_command
    print(cap_doc[:1000] + ('...' if len(cap_doc) > 1000 else ''), file=sys.stderr)
          ~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
TypeError: can't concat str to bytes
```
occurs. Following WMTS capabilities URL was used `https://geoservices.bayern.de/od/wmts/geobasis/v1/1.0.0/WMTSCapabilities.xml` (but it also did not work properly with other capabilities files with `.xml` ending).

## Context

Using the provided source WMTS URL `https://geoservices.bayern.de/od/wmts/geobasis/v1/1.0.0/WMTSCapabilities.xml` via other tools like QGIS does work correctly and load all respective layers without issues, therefore it does not look like WMTS source error.

## Expected Behavior

An appropriate mapproxy config should have been generated without issues.

## Actual Behavior

Above-mentioned error is thrown and no config is created.

## Steps to Reproduce
1. Run `mapproxy-util autoconfig --capabilities https://geoservices.bayern.de/od/wmts/geobasis/v1/1.0.0/WMTSCapabilities.xml`

## Your Environment

Using dockerized version of mapproxy: `kartoza/mapproxy:latest`
mapproxy version: 1.16.0
Python version: 3.11.5

**Comment by simonseyock** [comment]
Looking at the documentation and the code I'd say it is not possible to use a WMTS Capabilities here. Only WMS Capabilities are supported.

**Comment by simonseyock** [comment]
See http://mapproxy.github.io/mapproxy/mapproxy_util_autoconfig.html#cmdoption-mapproxy-util-autoconfig-capabilities

**Comment by simonseyock** [comment]
I added a more specific error message here: https://github.com/mapproxy/mapproxy/pull/867 and also fixed the other error that occurred.

Thank you very much for reporting!
