### ISSUE TITLE
Docker image ghcr.io/mapproxy/mapproxy/mapproxy:2.0.2-dev doesn't contain necessary pip packages

### ISSUE THREAD

**Issue by Dronis2000** [mapproxy/mapproxy#900]
Image ghcr.io/mapproxy/mapproxy/mapproxy:2.0.2-dev gets error on startup:
`Found libproj >=5. Using this library without pyproj is deprecated and not fully supported. Please install pyproj >= 2.
Traceback (most recent call last):
  File "/usr/local/bin/mapproxy-util", line 5, in <module>
    from mapproxy.script.util import main
  File "/usr/local/lib/python3.10/site-packages/mapproxy/script/util.py", line 29, in <module>
    from mapproxy.script.conf.app import config_command
  File "/usr/local/lib/python3.10/site-packages/mapproxy/script/conf/app.py", line 32, in <module>
    from .sources import sources
  File "/usr/local/lib/python3.10/site-packages/mapproxy/script/conf/sources.py", line 17, in <module>
    from mapproxy.srs import SRS
  File "/usr/local/lib/python3.10/site-packages/mapproxy/srs.py", line 26, in <module>
    from mapproxy.proj import USE_PROJ4_API
  File "/usr/local/lib/python3.10/site-packages/mapproxy/proj.py", line 282, in <module>
    res = try_import()
  File "/usr/local/lib/python3.10/site-packages/mapproxy/proj.py", line 155, in try_libproj_import
    libproj = init_libproj()
  File "/usr/local/lib/python3.10/site-packages/mapproxy/proj.py", line 66, in init_libproj
    libproj.pj_init_plus.argtypes = [c_char_p]
  File "/usr/local/lib/python3.10/ctypes/__init__.py", line 387, in __getattr__
    func = self.__getitem__(name)
  File "/usr/local/lib/python3.10/ctypes/__init__.py", line 392, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: /lib/x86_64-linux-gnu/libproj.so.25: undefined symbol: pj_init_plus`

## Context
I tried to run the dev docker image (ghcr.io/mapproxy/mapproxy/mapproxy:2.0.2-dev) in Kubernetes. The container started, but didn't display home page on port 8080. Logs contain error (see above).

## Expected Behavior
I can see MapProxy homepage on port 8080.

## Actual Behavior
The port 8080 is unaccessible.

## Possible Fix
To fix the problem I added pip packages pyproj and boto3 to docker image and saved new image to my local docker registry. My Dockerfile:
`FROM ghcr.io/mapproxy/mapproxy/mapproxy:2.0.2-dev`
`RUN pip3 install pyproj boto3 `

## Steps to Reproduce

1. 
2.
3.
4.

## Your Environment

* Version used: 2.0.2, docker image ghcr.io/mapproxy/mapproxy/mapproxy:2.0.2-dev

**Comment by simonseyock** [comment]
I can reproduce the error and will work on a fix.

**Comment by simonseyock** [comment]
I created this PR for this: https://github.com/mapproxy/mapproxy/pull/909

is the boto3 dependency really needed to run mapproxy or is this something needed for additional functionality?

**Comment by shimoncohen** [comment]
> I created this PR for this: #909
> 
> is the boto3 dependency really needed to run mapproxy or is this something needed for additional functionality?

The boto3 is used for `s3` caches which I would consider a core part in mapproxy (cannot differentiate between different cache types). There is an option to use `http` instead of boto, but I think boto is the default.

**Comment by simonseyock** [comment]
Sorry for the late response, but I was not sure before if my fix was applicable in the first place. What version of boto3 should be included? `==1.34` would be the current one. Or can we use `>=1` or something to make builds with older python versions possible? @weskamm can you say something about this?

**Comment by weskamm** [comment]
builds passed for all supported python versions with 1.34 before, so no need to lower that

**Comment by simonseyock** [comment]
This should work now, all required libraries are included in the docker image: https://github.com/mapproxy/mapproxy/blob/master/Dockerfile#L50
