### ISSUE TITLE
Coverages: File with webmercator tile coordinates

### ISSUE THREAD

**Issue by CaptainInler** [mapproxy/mapproxy#932]
## Context
The Documentation mentions as a possible way to define a coverage [a file with webmercator tile coordinates](https://github.com/mapproxy/mapproxy/blob/444354931a625688d8ca435234dc4e45ad721a25/doc/coverages.rst?plain=1#L16)
unfortunately there is no description or example on how this file should look like.

## Expected Behavior
The documentation about coverage should have an example of `a file with webmercator tile coordinates` if this option still exists.

## Actual Behavior
No existing documentation about this option available yet

**Comment by simonseyock** [comment]
You can find the documentation a little further below in the same file:

https://mapproxy.github.io/mapproxy/latest/coverages.html#expire-tiles
