### ISSUE TITLE
Dockerfile CMD instead of ENTRYPOINT

### ISSUE THREAD

**Issue by simonseyock** [mapproxy/mapproxy#937]
It would be nicer if the Dockerfile used a CMD instead of an ENTRYPOINT command to start it's service.

It normally is good practice to do setup work in the entrypoint script and at the end just run the cmd, which will be passed as an argument with `exec "$@"`.

This would make it nicer to use the image for seeding with:
```
docker run mapproxy mapproxy-seed -f mapproxy.yaml -s seed.yaml
```

instead of
```
docker run --entrypoint /usr/local/bin/mapproxy-seed mapproxy -f mapproxy.yaml -s seed.yaml
```

which misses some setup work done in the entrypoint script.

**Comment by weskamm** [comment]
Sounds good, please just go ahead
